('7'),
('?'),
('3-Hump Lacooda'),
('4-Starred Ladybug of Doom'),
('7 Colored Fish'),
('7 Completed'),
('7-Colored Fish'),
('8-Claws Scorpion'),
('A Cat of Ill Omen'),
('A Cell Breeding Device'),
('A Cell Incubator'),
('A Cell Scatter Burst'),
('A Deal with Dark Ruler'),
('A Feather of the Phoenix'),
('A Feint Plan'),
('A Hero Emerges'),
('A legendary Ocean'),
('A Legendary Ocean'),
('A Major Upset'),
('A Man with Wdjat'),
('A Rival Appears!'),
('A Wingbeat of Giant Dragon'),
('A-Team: Trap Disposal Unit'),
('Abaki'),
('Abare Ushioni'),
('Absolute End'),
('Absorbing Kid from the Sky'),
('Abyss Soldier'),
('Abyssal Designator'),
('Abyssal Kingshark'),
('Accumulated Fortune'),
('Acid Rain'),
('Acid Trap Hole'),
('Acidic Downpour'),
('Acrobat Monkey'),
('Adhesion Trap Hole'),
('Adhesive Explosive'),
('Advance Draw'),
('Advance Force'),
('Advanced Ritual Art'),
('Aegis of Gaia'),
('Aegis of the Ocean Dragon Lord'),
('After Genocide'),
('After the Struggle'),
('Against the Wind'),
('Agido'),
('Airknight Parshath'),
('Aitsu'),
('Alchemist of Black Spells'),
('Alchemy Cycle'),
('Alien Ammonite'),
('Alien Brain'),
('Alien Dog'),
('Alien Grey'),
('Alien Hunter'),
('Alien Hypno'),
('Alien Infiltrator'),
('Alien Kid'),
('Alien Mars'),
('Alien Mother'),
('Alien Overlord'),
('Alien Psychic'),
('Alien Shocktrooper'),
('Alien Skull'),
('Alien Telepath'),
('Alien Warrior'),
('All-Out Attacks '),
('Allure of Darkness'),
('Allure Queen LV3'),
('Allure Queen LV5'),
('Allure Queen LV7'),
('Ally of Justice Catastor'),
('Ally of Justice Clausolas'),
('Ally of Justice Garadholg'),
('Ally of Justice Rudra'),
('Alpha the Magnet Warrior'),
('Altar for Tribute'),
('Amazon Archer'),
('Amazon of the Seas'),
('Amazoness Archers'),
('Amazoness Blowpiper'),
('Amazoness Chain Master'),
('Amazoness Fighter'),
('Amazoness Paladin'),
('Amazoness Spellcaster'),
('Amazoness Swords Woman'),
('Amazoness Tiger'),
('Ambulance Rescueroid'),
('Ambulanceroid'),
('Ambush Fangs'),
('Ameba'),
('Amphibian Beast'),
('Amphibious Bugroth'),
('Amphibious Bugroth Mk-3'),
('Amphibious Bugroth MK-3'),
('Amplifier'),
('Amulet of Ambition'),
('An Owl of Luck'),
('An Unfortunate Report'),
('Ancient Brain'),
('Ancient City - Rainbow Ruins'),
('Ancient City – Rainbow Ruins'),
('Ancient Crimson Ape'),
('Ancient Elf'),
('Ancient Fairy Dragon'),
('Ancient Forest'),
('Ancient Gear'),
('Ancient Gear Beast'),
('Ancient Gear Cannon'),
('Ancient Gear Castle'),
('Ancient Gear Drill'),
('Ancient Gear Engineer'),
('Ancient Gear Explosive'),
('Ancient Gear Factory'),
('Ancient Gear Fist'),
('Ancient Gear Gadjiltron Chimera'),
('Ancient Gear Gadjiltron Dragon'),
('Ancient Gear Golem'),
('Ancient Gear Knight'),
('Ancient Gear Soldier'),
('Ancient Gear Tank'),
('Ancient Gear Workshop'),
('Ancient Lamp'),
('Ancient Leaf'),
('Ancient Lizard Warrior'),
('Ancient One of the Deep Forest'),
('Ancient Rules'),
('Ancient Sacred Wyvern'),
('Ancient Telescope'),
('Andro Sphinx'),
('Angel O7'),
('Ansatsu'),
('Ante'),
('Anteatereatingant'),
('Anti Raigeki'),
('Anti-Aircraft Flower'),
('Anti-Fusion Device'),
('Anti-Spell'),
('Anti-Spell Fragrance'),
('Apocatequil'),
('Appointer of the Red Lotus'),
('Apprentice Magician'),
('Appropriate'),
('Aqua Chorus'),
('Aqua Dragon'),
('Aqua Madoor'),
('Aqua Spirit'),
('Aquarian Alessa'),
('Arcana Call'),
('Arcana Force 0 - The Fool'),
('Arcana Force EX - The Dark Ruler'),
('Arcana Force I - The Magician'),
('Arcana Force III - The Empress'),
('Arcana Force IV - The Emperor'),
('Arcana Force VI - The Lovers'),
('Arcana Force VII - The Chariot'),
('Arcana Force XIV - Temperance'),
('Arcana Force XVIII - The Moon'),
('Arcana Force XXI - The World'),
('Arcana Knight Joker'),
('Arcane Apprentice'),
('Arcane Archer of the Forest'),
('Arcane Barrier'),
('Arcanite Magician'),
('Arcanite Magician/Assault Mode'),
('Archfiend General'),
('Archfiend Marmot of Nefariousness'),
('Archfiend of Gilfer'),
('Archfiend Soldier'),
('Archfiend Zombie-Skull'),
('Archfiend''s Oath'),
('Archfiend''s Roar'),
('Archlord Kristya'),
('Archlord Zerato'),
('Armageddon Knight'),
('Armaill'),
('Armed Changer'),
('Armed Dragon LV10'),
('Armed Dragon LV3'),
('Armed Dragon LV5'),
('Armed Dragon LV7'),
('Armed Ninja'),
('Armed Samurai - Ben Kei'),
('Armed Sea Hunter'),
('Armityle the Chaos Phantom'),
('Armor Break'),
('Armor Breaker'),
('Armor Exe'),
('Armored Axon Kicker'),
('Armored Cybern'),
('Armored Glass'),
('Armored Lizard'),
('Armored Starfish'),
('Armored Zombie'),
('Armoroid'),
('Armory Arm'),
('Array of Revealing Light'),
('Arsenal Bug'),
('Arsenal Robber'),
('Arsenal Summoner'),
('Ascending Soul'),
('Assault Armor'),
('Assault Beast'),
('Assault Counter'),
('Assault Mercenary'),
('Assault Mode Activate'),
('Assault on GHQ'),
('Assault Overload'),
('Assault Revival'),
('Assault Slash'),
('Assault Teleport'),
('Astral Barrier'),
('Asura Priest'),
('Aswan Apparition'),
('At One With the Sword'),
('Athena'),
('Atlantean Pikeman'),
('Atlantean Pikeman '),
('Atomic Firefly'),
('Attack and Receive'),
('Attack of the Cornered Rat'),
('Attack Pheromones'),
('Attack Reflector Unit'),
('Aurkus, Lightsworn Druid'),
('Aussa the Earth Charmer'),
('Automatic Laser'),
('Autonomous Action Unit'),
('Avalanching Aussa'),
('Avatar of the Pot'),
('Avatar of The Pot'),
('Avenging Knight Parshath'),
('Axe of Despair'),
('Axe Raider'),
('B. Skull Dragon'),
('B.E.S. Big Core MK-2'),
('B.E.S. Covered Core'),
('B.E.S. Crystal Core'),
('B.E.S. Tetran'),
('Baby Dragon'),
('Babycerasaurus'),
('Back to Square One'),
('Backfire'),
('Backs to the Wall'),
('Backup Soldier'),
('Bad Reaction to Simochi'),
('Bait Doll'),
('Ballista of Rampart Smashing'),
('Balloon Lizard'),
('Bamboo Scrap'),
('Banisher of the Light'),
('Banisher of the Radiance'),
('Banner of Courage'),
('Bark of Dark Ruler'),
('Baron of the Fiend Sword'),
('Barrel Behind the Door'),
('Barrel Dragon'),
('Barrier Statue of the Abyss'),
('Barrier Statue of the Drought'),
('Barrier Statue of the Heavens'),
('Barrier Statue of the Inferno'),
('Barrier Statue of the Stormwinds'),
('Barrier Statue of the Torrent'),
('Basic Insect'),
('Battery Charger'),
('Batteryman AA'),
('Batteryman C'),
('Batteryman Charger'),
('Batteryman D'),
('Batteryman Industrial Strength'),
('Batteryman Micro-Cell'),
('Battle Fader'),
('Battle Footballer'),
('Battle Mania'),
('Battle of the Elements'),
('Battle Ox'),
('Battle Steer'),
('Battle Teleportation'),
('Battle Tuned'),
('Battle-Scarred'),
('Battlestorm'),
('Bazoo the Soul-Eater'),
('Bazoo the Soul–Eater'),
('Bean Soldier'),
('Beast Fangs'),
('Beast King Barbaros'),
('Beast Machine King Barbaros Ur'),
('Beast of Talwar'),
('Beast of the Pharaoh'),
('Beast Soul Swap'),
('Beast Striker'),
('Beastking of the Swamps'),
('Beautiful Headhuntress'),
('Beaver Warrior'),
('Beckoning Light'),
('Bee List Soldier'),
('Beelze Frog'),
('Begone, Knave!'),
('Behegon'),
('Behemoth the King of All Animals'),
('Beiige, Vanguard of Dark World'),
('Belial - Marquis of Darkness'),
('Bending Destiny'),
('Berfomet'),
('Berserk Dragon'),
('Berserk Gorilla'),
('Berserker Crush'),
('Berserking'),
('Beta the Magnet Warrior'),
('Bickuribox'),
('Bicular'),
('Big Bang Shot'),
('Big Burn'),
('Big Core'),
('Big Evolution Pill'),
('Big Eye'),
('Big Koala'),
('Big Piece Golem'),
('Big Shield Gardna'),
('Big Wave Small Wave'),
('Big-Tusked Mammoth'),
('Bio-Mage'),
('Birdface'),
('Birthright'),
('Bite Shoes'),
('Bitelon'),
('Black Brutdrago'),
('Black Garden'),
('Black Horn of Heaven'),
('Black Illusion Ritual'),
('Black Luster Ritual'),
('Black Luster Soldier'),
('Black Luster Soldier - Envoy of the Beginning'),
('Black Magic Ritual'),
('Black Pendant'),
('Black Potan'),
('Black Ptera'),
('Black Rose Dragon'),
('Black Salvo'),
('Black Stego'),
('Black Tyranno'),
('Black Veloci'),
('Black Whirlwind'),
('Blackland Fire Dragon'),
('Blackwing - Blizzard the Far North'),
('Blackwing - Bora the Spear'),
('Blackwing - Elphin the Raven'),
('Blackwing - Fane the Steel Chain'),
('Blackwing - Gale the Whirlwind'),
('Blackwing - Kalut the Moon Shadow'),
('Blackwing - Mistral the Silver Shield'),
('Blackwing - Shura the Blue Flame'),
('Blackwing - Silverwind the Ascendant'),
('Blackwing - Sirocco the Dawn'),
('Blackwing - Vayu the Emblem of Honor'),
('Blackwing Armed Wing'),
('Blackwing Armor Master'),
('Blade Knight'),
('Blade Rabbit'),
('Blade Skater'),
('Bladefly'),
('Blast Asmodian'),
('Blast Held by a Tribute'),
('Blast Juggler'),
('Blast Magician'),
('Blast Sphere'),
('Blast with Chain'),
('Blasting Fuse'),
('Blasting the Ruins'),
('Blaze Accelerator'),
('Blazewing Butterfly'),
('Blazing Hiita'),
('Blazing Inpachi'),
('Blessings of the Nile'),
('Blind Destruction'),
('Blindly Loyal Goblin'),
('Blizzard Dragon'),
('Blizzard Warrior'),
('Blizzed, Defender of the Ice Barrier'),
('Block Attack'),
('Blocker'),
('Blockman'),
('Blowback Dragon'),
('Blue Eyes Ultimate Dragon'),
('Blue Eyes White Dragon'),
('Blue Medicine'),
('Blue Thunder T45'),
('Blue-Eyes Shining Dragon'),
('Blue-Eyes Toon Dragon'),
('Blue-Eyes Ultimate Dragon'),
('Blue-Eyes White Dragon'),
('Blue-Winged Crown'),
('Blue–Eyes Ultimate Dragon'),
('Boar Soldier'),
('Bokoichi the Freightening Car'),
('Bombardment Beetle'),
('Bonding - H2O'),
('Bone Crusher'),
('Bone Temple Block'),
('Boneheimer'),
('Book of Eclipse'),
('Book of Life'),
('Book of Moon'),
('Book of Secret Arts'),
('Book of Taiyou'),
('Booster Box'),
('Booster Pack'),
('Boot-Up Soldier - Dread Dynamo'),
('Boss Rush'),
('Botanical Girl'),
('Botanical Lion'),
('Bottom Dweller'),
('Bottomless Shifting Sand'),
('Bottomless Trap Hole'),
('Bountiful Artemis'),
('Bowganian'),
('Brain Control'),
('Brain Crusher'),
('Brain Golem'),
('Brain Jacker'),
('Brain Research Lab'),
('Brainwashing Beam'),
('Branch!'),
('Break! Draw!'),
('Breaker the Magical Warrior'),
('Breakthrough!'),
('Breath of Light'),
('Brionac, Dragon of the Ice Barrier'),
('Broken Bamboo Sword'),
('Broken Blocker'),
('Broww, Huntsman of Dark World'),
('Brron, Mad King of Dark World'),
('Bubble Blaster'),
('Bubble Crash'),
('Bubble Illusion'),
('Bubble Shuffle'),
('Bubonic Vermin'),
('Burden of the Mighty'),
('Burglar'),
('Burial from a Different Dimension'),
('Burning Algae'),
('Burning Beast'),
('Burning Land'),
('Burning Spear'),
('Burst Breath'),
('Burst Return'),
('Burst Stream of Destruction'),
('Buster Blader'),
('Buster Rancher'),
('Butterfly Dagger - Elma'),
('By Order of the Emperor'),
('Byroad Sacrifice'),
('Byser Shock'),
('Cactus Bouncer'),
('Cactus Fighter'),
('Caius the Shadow Monarch'),
('Call of Darkness'),
('Call of the Grave'),
('Call Of The Haunted'),
('Call of the Mummy'),
('Call of the Reaper'),
('Calming Magic'),
('Cannon Soldier'),
('Cannon Soldier MK-2'),
('Cannonball Spear Shellfish'),
('Canyon'),
('Card Blocker'),
('Card Destruction'),
('Card Ejector'),
('Card Guard'),
('Card of Safe Return'),
('Card of Sanctity'),
('Card Rotator'),
('Card Shuffle'),
('Card Trader'),
('Card Trooper'),
('Cards of Consonance'),
('Carrierroid'),
('Castle of Dark Illusions'),
('Castle Walls'),
('Cat''s Ear Tribe'),
('Catapult Turtle'),
('Catnipped Kitty'),
('Catoblepas and the Witch of Fate'),
('Cave Dragon'),
('Ceasefire'),
('Celestia, Lightsworn Angel'),
('Celestial Transformation'),
('Cell Explosion Virus'),
('Celtic Guardian'),
('Cemetery Bomb'),
('Centrifugal Field'),
('Ceremonial Bell'),
('Cestus of Dagla'),
('Chain Burst'),
('Chain Destruction'),
('Chain Detonation'),
('Chain Disappearance'),
('Chain Energy'),
('Chain Healing'),
('Chain Material'),
('Chain Strike'),
('Chain Summoning'),
('Chain Thrasher'),
('Chainsaw Insect'),
('Chamberlain of the Six Samurai'),
('Change of Heart'),
('Change of Hero - Reflector Ray'),
('Changing Destiny'),
('Chaos Burst'),
('Chaos Command Magician'),
('Chaos Emperor Dragon - Envoy of the End'),
('Chaos End'),
('Chaos End Master'),
('Chaos Greed'),
('Chaos Necromancer'),
('Chaos Sorcerer'),
('Chaosrider Gustaph'),
('Charcoal Inpachi'),
('Charge of the Light Brigade'),
('Charm of Shabti'),
('Charubin the Fire Knight'),
('Checkmate'),
('Chimaera, the Master of Beasts'),
('Chimera the Flying Mythical Beast'),
('Chimeratech Fortress Dragon'),
('Chimeratech Overdragon'),
('Chiron the Mage'),
('Chopman the Desperate Outlaw'),
('Chorus of Sanctuary'),
('Chosen One'),
('Chrysalis Chicky'),
('Chrysalis Dolphin'),
('Chrysalis Larva'),
('Chrysalis Mole'),
('Chrysalis Pantail'),
('Chrysalis Pinny'),
('Chthonian Alliance'),
('Chthonian Blast'),
('Chthonian Emperor Dragon'),
('Chthonian Polymer'),
('Chthonian Soldier'),
('Chu-Ske The Mouse Fighter'),
('Chu-Ske the Mouse Fighter'),
('Claw Reacher'),
('Clay Charge'),
('Clear Vice Dragon'),
('Clear World'),
('Cliff the Trap Remover'),
('Cloak and Dagger'),
('Clock Tower Prison'),
('Cloning'),
('Cloudian - Acid Cloud'),
('Cloudian - Altus'),
('Cloudian - Cirrostratus'),
('Cloudian - Eye of the Typhoon'),
('Cloudian - Ghost Fog'),
('Cloudian - Nimbusman'),
('Cloudian - Poison Cloud'),
('Cloudian - Sheep Cloud'),
('Cloudian - Smoke Ball'),
('Cloudian - Storm Dragon'),
('Cloudian - Turbulence'),
('Cloudian Squall'),
('Clown Zombie'),
('Coach Goblin'),
('Cobra Jar'),
('Cobraman Sakuzy'),
('Cockroach Knight'),
('Cocoon of Evolution'),
('Cocoon Party'),
('Cocoon Rebirth'),
('Cocoon Veil'),
('Codarus'),
('Code A Ancient Ruins'),
('Coffin Seller'),
('Cold Enchanter'),
('Cold Wave'),
('Collected Power'),
('Colossal Fighter'),
('Colossal Fighter/Assault Mode'),
('Colosseum - Cage of the Gladiator Beasts'),
('Combination Attack'),
('Combo Fighter'),
('Combo Master'),
('Command Knight'),
('Commander Covington'),
('Commander Gottoms - Swordmaster'),
('Commencement Dance'),
('Common Charity'),
('Common Soul'),
('Compulsory Evacuation Device'),
('Comrade Swordsman of Landstar'),
('Confiscation'),
('Confusion Chaff'),
('Conscription'),
('Consecrated Light'),
('Contact'),
('Contact Out'),
('Continuous Destruction Punch'),
('Contract with Exodia'),
('Contract with the Abyss'),
('Contract with the Dark Master'),
('Convert Contact'),
('Convulsion of Nature'),
('Copy Plant'),
('Copycat'),
('Core Blast'),
('Core Blaster'),
('Core Compression'),
('Core Reinforcement'),
('Core Transport Unit'),
('Corroding Shark'),
('Corruption Cell A'),
('Cosmic Fortress Gol''Gar'),
('Cosmic Horror Gangi''el'),
('Cosmo Queen'),
('Cost Down'),
('Counselor Lily'),
('Counter Cleaner'),
('Counter Counter'),
('Covering Fire'),
('Crab Turtle'),
('Cranium Fish'),
('Crass Clown'),
('Crawling Dragon'),
('Crawling Dragon #2'),
('Creature Seizure'),
('Creature Swap'),
('Creeping Doom Manta'),
('Crimson Fire'),
('Crimson Ninja'),
('Crimson Sentry'),
('Criosphinx'),
('Crop Circles'),
('Cross Counter'),
('Cross Porter'),
('Cross-Sword Beetle'),
('Crusader of Endymion'),
('Crush Card Virus'),
('Cry Havoc!'),
('Cryomancer of the Ice Barrier'),
('Crystal Abundance'),
('Crystal Beacon'),
('Crystal Beast Amber Mammoth'),
('Crystal Beast Amethyst Cat'),
('Crystal Beast Cobalt Eagle'),
('Crystal Beast Emerald Tortoise'),
('Crystal Beast Ruby Carbuncle'),
('Crystal Beast Sapphire Pegasus'),
('Crystal Beast Topaz Tiger'),
('Crystal Blessing'),
('Crystal Counter'),
('Crystal Pair'),
('Crystal Promise'),
('Crystal Raigeki'),
('Crystal Release'),
('Crystal Seer'),
('Crystal Tree'),
('Cú Chulainn the Awakened'),
('Cunning of the Six Samurai'),
('Cup of Ace'),
('Cure Mermaid'),
('Curse of Aging'),
('Curse of Anubis'),
('Curse of Darkness'),
('Curse of Dragon'),
('Curse of Fiend'),
('Curse of Royal'),
('Curse of the Masked Beast'),
('Cursed Fig'),
('Cursed Seal of the Forbidden Spell'),
('Cyber Archfiend'),
('Cyber Barrier Dragon'),
('Cyber Blader'),
('Cyber Dragon'),
('Cyber Dragon Zwei'),
('Cyber End Dragon'),
('Cyber Esper'),
('Cyber Falcon'),
('Cyber Gymnast'),
('Cyber Harpie Lady'),
('Cyber Jar'),
('Cyber Kirin'),
('Cyber Laser Dragon'),
('Cyber Ogre'),
('Cyber Ogre 2'),
('Cyber Ouroboros'),
('Cyber Phoenix'),
('Cyber Prima'),
('Cyber Raider'),
('Cyber Saurus'),
('Cyber Shadow Gardna'),
('Cyber Shark'),
('Cyber Soldier of Darkworld'),
('Cyber Summon Blaster'),
('Cyber Tutu'),
('Cyber Twin Dragon'),
('Cyber Valley'),
('Cyber-Stein'),
('Cyber-Tech Alligator'),
('Cyberdark Dragon'),
('Cyberdark Edge'),
('Cyberdark Horn'),
('Cyberdark Impact!'),
('Cyberdark Keel'),
('Cybernetic Cyclopean'),
('Cybernetic Hidden Technology'),
('Cybernetic Magician'),
('Cybernetic Zone'),
('Cyborg Doctor'),
('Cycloid'),
('Cyclon Laser'),
('Cyclone Blade'),
('Cyclone Boomerang'),
('Cycroid'),
('D - Chain'),
('D - Counter'),
('D - Formation'),
('D - Fortune'),
('D - Shield'),
('D - Spirit'),
('D - Time'),
('D.  D. Designator'),
('D. D. Assailant'),
('D. D. Crazy Beast'),
('D. D. Dynamite'),
('D. D. Survivor'),
('D. D. Trainer'),
('D. D. Warrior Lady'),
('D. Human'),
('D. Tribe'),
('D.3.S. Frog'),
('D.D. Assailant'),
('D.D. Borderline'),
('D.D. Crazy Beast'),
('D.D. Crow'),
('D.D. Designator'),
('D.D. Dynamite'),
('D.D. Guide'),
('D.D. Scout Plane'),
('D.D. Survivor'),
('D.D. Trap Hole'),
('D.D. Warrior'),
('D.D. Warrior Lady'),
('D.D.M. - Different Dimension Master'),
('D.D.M. – Different Dimension Master'),
('D.D.R. - Different Dimension Reincarnation'),
('D.D.R. – Different Dimension Reincarnation'),
('Damage = Reptile'),
('Damage Condenser'),
('Damage Polarizer'),
('Damage Translation'),
('Dancing Elf'),
('Dancing Fairy'),
('Dandylion'),
('Dangerous Machine Type-6'),
('Dark Armed Dragon'),
('Dark Assailant'),
('Dark Balter the Terrible'),
('Dark Bat'),
('Dark Blade'),
('Dark Blade the Dragon Knight'),
('Dark Bribe'),
('Dark Bug'),
('Dark Calling'),
('Dark Cat with White Tail'),
('Dark Catapulter'),
('Dark City'),
('Dark Coffin'),
('Dark Core'),
('Dark Crusader '),
('Dark Deal'),
('Dark Designator'),
('Dark Driceratops'),
('Dark Dust Spirit'),
('Dark Effigy'),
('Dark Elf'),
('Dark End Dragon'),
('Dark Energy'),
('Dark Eradicator Warlock'),
('Dark Eruption '),
('Dark Factory of Mass Production'),
('Dark Flare Knight'),
('Dark Fusion'),
('Dark General Freed'),
('Dark Gray'),
('Dark Grepher'),
('Dark Hole'),
('Dark Horus'),
('Dark Horus '),
('Dark Hunter'),
('Dark Illusion'),
('Dark Jeroid'),
('Dark King of the Abyss'),
('Dark Lucius LV4'),
('Dark Lucius LV6'),
('Dark Lucius LV8'),
('Dark Magic Attack'),
('Dark Magician'),
('Dark Magician Curtain'),
('Dark Magician Girl'),
('Dark Magician Knight'),
('Dark Magician of Chaos'),
('Dark Master - Zorc'),
('Dark Mimic LV1'),
('Dark Mimic LV3'),
('Dark Mirror Force'),
('Dark Necrofear'),
('Dark Nephthys'),
('Dark Paladin'),
('Dark Rabbit'),
('Dark Red Enchanter'),
('Dark Resonator'),
('Dark Room of Nightmare'),
('Dark Ruler Ha Des'),
('Dark Sage'),
('Dark Scorpion - Chick the Yellow'),
('Dark Scorpion - Gorg the Strong'),
('Dark Scorpion - Meanae the Thorn'),
('Dark Scorpion Burglars'),
('Dark Scorpion Combination'),
('Dark Simorgh'),
('Dark Snake Syndrome'),
('Dark Spider'),
('Dark Spirit Art - Greed'),
('Dark Spirit of the Silent'),
('Dark Strike Fighter'),
('Dark Tinker'),
('Dark Titan of Terror'),
('Dark Valkyria'),
('Dark Valkyria '),
('Dark Verger'),
('Dark Voltanis'),
('Dark Witch'),
('Dark World Dealings'),
('Dark World Grimoire'),
('Dark World Lightning'),
('Dark Zebra'),
('Dark-Piercing Light'),
('Darkbishop Archfiend'),
('Darkblaze Dragon'),
('Darkfire Dragon'),
('Darkfire Soldier #1'),
('Darkfire Soldier #2'),
('Darklord Zerato'),
('Darkness Approaches'),
('Darknight Parshath'),
('Darknight Parshath '),
('Darksea Float'),
('Darksea Rescue'),
('Darkworld Thorns'),
('Dawnbreak Gardna'),
('De-Fusion'),
('De-Spell'),
('De-Synchro'),
('Deal of Phantom'),
('Debris Dragon'),
('Decayed Commander'),
('Deck Devastation Virus'),
('Deck Lockdown'),
('Decoy Dragon'),
('Decoyroid'),
('Dedication Through Light and Darkness'),
('Dedication through Light and Darkness'),
('Deep Diver'),
('Deep Sea Diva'),
('Deepsea Shark'),
('Deepsea Warrior'),
('Defender, The Magical Knight'),
('Defense Draw'),
('Defensive Tactics'),
('Degenerate Circuit'),
('Dekoichi the Battlechanted Locomotive'),
('Delinquent Duo'),
('Delta Attacker'),
('Delta Crow - Anti Reverse'),
('Demise of the Land'),
('Demise, King of Armageddon'),
('Demotion'),
('Depth Amulet'),
('Des Counterblow'),
('Des Croaking'),
('Des Dendle'),
('Des Feral Imp'),
('Des Frog'),
('Des Kangaroo'),
('Des Koala'),
('Des Lacooda'),
('Des Mosquito'),
('Des Volstgalph'),
('Des Wombat'),
('Descending Lost Star'),
('Desert Protector'),
('Desert Sunlight'),
('Desert Twister'),
('Desertapir'),
('Despair from the Dark'),
('Desrook Archfiend'),
('Destiny Board'),
('Destiny Draw'),
('Destiny End Dragoon'),
('Destiny Hero - Blade Master'),
('Destiny Hero - Captain Tenacious'),
('Destiny Hero - Dasher'),
('Destiny Hero - Defender'),
('Destiny Hero - Departed'),
('Destiny Hero - Diamond Dude'),
('Destiny Hero - Disk Commander'),
('Destiny Hero - Dogma'),
('Destiny Hero - Doom Lord'),
('Destiny Hero - Double Dude'),
('Destiny Hero - Dread Servant'),
('Destiny Hero - Dreadmaster'),
('Destiny Hero - Dunker'),
('Destiny Hero - Fear Monger'),
('Destiny Hero - Malicious'),
('Destiny Hero - Plasma'),
('Destiny Mirage'),
('Destiny Signal'),
('Destroyer Golem'),
('Destroyersaurus'),
('Destruct Potion'),
('Destruction Cyclone'),
('Destruction Jammer'),
('Destruction of Destiny'),
('Destruction Punch'),
('Destruction Ring'),
('Destructive Draw'),
('Destructotron'),
('Detonate'),
('Detonator Circle "A"'),
('Dharc the Dark Charmer'),
('Dharma Cannon'),
('Diabolos, King of the Abyss'),
('Diamond-Dust Cyclone'),
('Dian Keto the Cure Master'),
('Dice Jar'),
('Dice Re-Roll'),
('Dice Try! '),
('Different Dimension Capsule'),
('Different Dimension Dragon'),
('Different Dimension Gate'),
('Diffusion Wave-Motion'),
('Dig Beak'),
('Dimension Distortion'),
('Dimension Explosion'),
('Dimension Fortress Weapon'),
('Dimension Fusion'),
('Dimension Jar'),
('Dimension Wall'),
('Dimensional Alchemist'),
('Dimensional Fissure'),
('Dimensional Inversion'),
('Dimensional Prison'),
('Dimensionhole'),
('Disappear'),
('Disarm'),
('Disarmament'),
('Disc Fighter'),
('Disciple of the Forbidden Spell'),
('Discord'),
('Disenchanter'),
('Disk Magician'),
('Diskblade Rider '),
('Dissolverock'),
('Disturbance Strategy'),
('Divine Dragon Aquabizarre'),
('Divine Dragon Ragnarok'),
('Divine Dragon-Excelion'),
('Divine Grace - Northwemko'),
('Divine Knight Ishzark'),
('Divine Sword - Phoenix Blade'),
('Divine Wrath'),
('Djinn Cursenchanter of Rituals'),
('Djinn Disserere of Rituals'),
('Djinn Presider of Rituals'),
('Djinn Prognosticator of Rituals'),
('Djinn Releaser of Rituals'),
('DNA Checkup'),
('DNA Surgery'),
('DNA Transplant'),
('Doctor Cranium'),
('Doitsu'),
('Dokurorider'),
('Dokuroyaiba'),
('Doma The Angel of Silence'),
('Domino Effect'),
('Don Turtle'),
('Don Zaloog'),
('Doom Dozer'),
('Doom Shaman'),
('Doomcaliber Knight'),
('Doomkaiser Dragon'),
('Doomkaiser Dragon/Assault Mode'),
('Doomsday Horror'),
('Doppelganger'),
('Dora of Fate'),
('Doriado''s Blessing'),
('Double Attack'),
('Double Coston'),
('Double Snare'),
('Double Spell'),
('Double Summon'),
('Double Tag Team'),
('Double Tool C&D'),
('Double-Edged Sword Technique'),
('Dragged Down into the Grave'),
('Dragon Capture Jar'),
('Dragon Ice'),
('Dragon Manipulator'),
('Dragon Master Knight'),
('Dragon Piper'),
('Dragon Queen of Tragic Endings'),
('Dragon Seeker'),
('Dragon Treasure'),
('Dragon Zombie'),
('Dragon''s Gunfire'),
('Dragon''s Mirror'),
('Dragon''s Rage'),
('Dragoness the Wicked Knight'),
('Dragonic Attack'),
('Dragonic Guard'),
('Dragonic Knight'),
('Draining Shield'),
('Dramatic Rescue'),
('Drastic Drop Off'),
('Dreadscythe Harvester'),
('Dream Clown'),
('Dreamsprite'),
('Drill Bug'),
('Drill Synchron'),
('Drill Warrior'),
('Drillago'),
('Drillroid'),
('Driving Snow'),
('Drooling Lizard'),
('Drop Off'),
('DUCKER Mobile Cannon'),
('Dummy Golem'),
('Dunames Dark Witch'),
('Dungeon Worm'),
('Dupe Frog'),
('Dust Barrier'),
('Dust Tornado'),
('Dweller in the Depths'),
('E - Emergency Call'),
('Eagle Eye'),
('Earth Chant'),
('Earth Effigy'),
('Earthbound Immortal Aslla Piscu'),
('Earthbound Immortal Ccapac Apu'),
('Earthbound Immortal Ccarayhua'),
('Earthbound Immortal Chacu Challhua'),
('Earthbound Immortal Cusillu'),
('Earthbound Immortal Uru'),
('Earthbound Immortal Wiraqocha Rasca'),
('Earthbound Linewalker'),
('Earthbound Revival'),
('Earthbound Spirit'),
('Earthbound Wave'),
('Earthbound Whirlwind'),
('Earthquake'),
('Earthshaker'),
('Eatgaboon'),
('Ebon Arrow'),
('Ebon Magician Curran'),
('Eccentric Boy'),
('Ectoplasmer'),
('Edge Hammer'),
('Ehren, Lightsworn Monk'),
('Ekibyo Drakmord'),
('Electric Lizard'),
('Electric Snake'),
('Electric Virus'),
('Electro-Whip'),
('Elegant Egotist'),
('Element Doom'),
('Element Dragon'),
('Element Magician'),
('Element Saurus'),
('Element Soldier'),
('Element Valkyrie'),
('Elemental Absorber'),
('Elemental Burst'),
('Elemental Hero Air Neos'),
('Elemental Hero Aqua Neos'),
('Elemental Hero Avian'),
('Elemental Hero Bladedge'),
('Elemental Hero Bubbleman'),
('Elemental Hero Burstinatrix'),
('Elemental Hero Captain Gold'),
('Elemental Hero Chaos Neos'),
('Elemental Hero Clayman'),
('Elemental Hero Dark Neos'),
('Elemental Hero Darkbright'),
('Elemental Hero Divine Neos'),
('Elemental Hero Electrum'),
('Elemental Hero Flame Wing Man'),
('Elemental Hero Flame Wingman'),
('Elemental Hero Flare Neos'),
('Elemental Hero Gaia'),
('Elemental Hero Glow Neos'),
('Elemental Hero Grand Neos'),
('Elemental Hero Heat'),
('Elemental Hero Inferno'),
('Elemental Hero Knospe'),
('Elemental Hero Lady Heat'),
('Elemental Hero Magma Neos'),
('Elemental Hero Marine Neos'),
('Elemental Hero Mariner'),
('Elemental Hero Mudballman'),
('Elemental Hero Necroid Shaman'),
('Elemental Hero Necroshade'),
('Elemental Hero Neo Bubbleman'),
('Elemental Hero Neos'),
('Elemental Hero Neos Alius'),
('Elemental Hero Ocean'),
('Elemental Hero Phoenix Enforcer'),
('Elemental Hero Plasma Vice'),
('Elemental Hero Poison Rose'),
('Elemental Hero Prisma'),
('Elemental Hero Rampart Blaster'),
('Elemental Hero Shining Flare Wingman'),
('Elemental Hero Shining Phoenix Enforcer'),
('Elemental Hero Sparkman'),
('Elemental Hero Steam Healer'),
('Elemental Hero Storm Neos'),
('Elemental Hero Stratos'),
('Elemental Hero Tempest'),
('Elemental Hero Terra Firma'),
('Elemental Hero Thunder Giant'),
('Elemental Hero Voltic'),
('Elemental Hero Wild Wingman'),
('Elemental Hero Wildedge'),
('Elemental Hero Wildheart'),
('Elemental Hero Woodsman'),
('Elemental Mistress Doriado'),
('Elemental Recharge'),
('Elephant Statue of Blessing'),
('Elephant Statue of Disaster'),
('Elf''s Light'),
('Eliminating the League'),
('Emblem of Dragon Destroyer'),
('Emblem of the Awakening'),
('Embodiment of Apophis'),
('Emergency Assistance'),
('Emergency Provisions'),
('Emergency Teleport'),
('Emes the Infinity'),
('Emissary from Pandemonium'),
('Emissary of the Afterlife'),
('Emissary of the Oasis'),
('Emperor of Lightning'),
('Emperor Sem'),
('Empress Judge'),
('Empress Mantis'),
('Enchanted Javelin'),
('Enchanting Fitting Room'),
('Enchanting Mermaid'),
('End of the World'),
('Endymion, The Master Magician'),
('Enemy Controller'),
('Energy Absorbing Monolith'),
('Energy Bravery'),
('Energy Drain'),
('Enervating Mist'),
('Enishi, Shien''s Chancellor'),
('Enlightenment'),
('Enraged Battle Ox'),
('Enraged Muka Muka'),
('Equip Shot'),
('Eradicator Epidemic Virus'),
('Eria the Water Charmer'),
('Escape from the Dark Dimension'),
('Eternal Dread'),
('Eternal Rest'),
('Etoile Cyber'),
('Everliving Underworld Cannon'),
('Evil Blast'),
('Evil Dragon Ananta'),
('Evil Hero Dark Gaia'),
('Evil Hero Infernal Gainer'),
('Evil Hero Infernal Prodigy'),
('Evil Hero Infernal Sniper'),
('Evil Hero Inferno Wing'),
('Evil Hero Lightning Golem'),
('Evil Hero Malicious Edge'),
('Evil Hero Malicious Fiend'),
('Evil Hero Wild Cyclone'),
('Evil Thorn'),
('Evocator Chevalier'),
('Evolution Burst'),
('Exarion Universe'),
('Exchange'),
('Exchange of the Spirit'),
('Exhausting Spell'),
('Exile of the Wicked'),
('Exiled Force'),
('Exodia Necross'),
('Exodia the Forbidden One'),
('Exploder Dragon'),
('Exploder Dragonwing'),
('Explosive Magician'),
('Expressroid'),
('Exxod, Master of the Guard'),
('Factory of 100 Machines'),
('Fairy Box'),
('Fairy Dragon'),
('Fairy Guardian'),
('Fairy King Truesdale'),
('Fairy Meteor Crush'),
('Fairy of the Spring'),
('Fairy Wind'),
('Fairy''s Gift'),
('Fairy''s Hand Mirror'),
('Faith Bird'),
('Fake Explosion'),
('Fake Feather'),
('Fake Hero'),
('Fake Trap'),
('Falchion Beta'),
('Falling Down'),
('Familiar Knight'),
('Familiar-Possessed - Aussa'),
('Familiar-Possessed - Eria'),
('Familiar-Possessed - Hiita'),
('Familiar-Possessed - Wynn'),
('Fatal Abacus'),
('Faustian Bargain'),
('Fear from the Dark'),
('Feather Shot'),
('Feather Wind'),
('Featherizer'),
('Felgrand Dragon'),
('Fengsheng Mirror'),
('Fenrir'),
('Feral Imp'),
('Fiber Jar'),
('Field Barrier'),
('Field-Commander Rahz'),
('Fiend Comedian'),
('Fiend Reflection #2'),
('Fiend Scorpion'),
('Fiend Skull Dragon'),
('Fiend''s Hand Mirror'),
('Fiend''s Sanctuary'),
('Fiendish Chain'),
('Fiendish Engine Omega'),
('Fifth Hope'),
('Fighting Spirit'),
('Final Attack Orders'),
('Final Countdown'),
('Final Destiny'),
('Final Flame'),
('Final Ritual of the Ancients'),
('Fine  '),
('Fire Ant Ascator'),
('Fire Darts'),
('Fire Kraken'),
('Fire Princess'),
('Fire Sorcerer'),
('Fire Trooper'),
('Firebird'),
('Firegrass'),
('Fires of Doomsday'),
('Firestorm Prominence'),
('Firewall'),
('Fireyarou'),
('Fish Depth Charge'),
('Fishborg Blaster'),
('Fissure'),
('Five-Headed Dragon'),
('Flame Cerebrus'),
('Flame Champion'),
('Flame Dancer'),
('Flame Ghost'),
('Flame Manipulator'),
('Flame Ogre'),
('Flame Ruler'),
('Flame Spirit Ignis'),
('Flame Swordsman'),
('Flame Viper'),
('Flamvell Commando'),
('Flamvell Counter'),
('Flamvell Drachnov'),
('Flamvell Firedog'),
('Flamvell Guard'),
('Flamvell Magician'),
('Flamvell Uruquizas'),
('Flash Assailant'),
('Flash of the Forbidden Spell'),
('Flashbang'),
('Flint'),
('Flint Lock'),
('Flint Missile'),
('Flip Flop Frog'),
('Flower Wolf'),
('Flying Fish'),
('Flying Fortress SKY FIRE'),
('Flying Kamakiri #1'),
('Flying Kamakiri #2'),
('Flying Penguin'),
('Flying Saucer Muusik''i'),
('Fog Control'),
('Fog King'),
('Follow Wind'),
('Foolish Burial'),
('Foolish Revival'),
('Forbidden Chalice'),
('Forced Back'),
('Forced Ceasefire'),
('Forced Requisition'),
('Forest'),
('Forgotten Temple of the Deep'),
('Formation Union'),
('Fortress Warrior'),
('Fortress Whale'),
('Fortress Whale''s Oath'),
('Fortune Lady Dark'),
('Fortune Lady Earth'),
('Fortune Lady Fire'),
('Fortune Lady Light'),
('Fortune Lady Water'),
('Fortune Lady Wind'),
('Fortune''s Future'),
('Fossil Dig'),
('Fossil Dyna Pachycephalo'),
('Fossil Excavation'),
('Fossil Tusker'),
('Fox Fire'),
('Fragrance Storm'),
('Freed the Brave Wanderer'),
('Freed the Brave Warrior'),
('Freed the Matchless General'),
('Freezing Beast'),
('Frenzied Panda'),
('Frequency Magician'),
('Freya, Spirit of Victory'),
('Frog The Jam'),
('Froggy Forcefield'),
('Frontier Wiseman'),
('Frontline Base'),
('Frost and Flame Dragon'),
('Frostosaurus'),
('Frozen Soul'),
('Fruits of Kozaky''s Studies'),
('Fuh-Rin-Ka-Zan'),
('Fuhma Shuriken'),
('Fulfillment of the Contract'),
('Full Salvo'),
('Fushi No Tori'),
('Fushioh Richie'),
('Fusilier Dragon, the Dual-Mode Beast'),
('Fusion Devourer'),
('Fusion Gate'),
('Fusion Guard'),
('Fusion Recovery'),
('Fusion Sage'),
('Fusion Sword Murasame Blade'),
('Fusion Weapon'),
('Fusionist'),
('Future Fusion'),
('Future Samurai'),
('Future Vision'),
('G.B. Hunter'),
('Gaap the Divine Soldier'),
('Gadget Arms'),
('Gadget Driver'),
('Gadget Hauler'),
('Gadget Soldier'),
('Gagagigo'),
('Gaia Knight, the Force of Earth'),
('Gaia Plate the Earth Giant'),
('Gaia Power'),
('Gaia Soul - The Combustible Collective'),
('Gaia Soul the Combustible Collective'),
('Gaia the Dragon Champion'),
('Gaia the Fierce Knight'),
('Gaia The Fierce Knight'),
('Gale Dogra'),
('Gale Lizard'),
('Gamble'),
('Gambler of Legend'),
('Gamma the Magnet Warrior'),
('Garlandolf, King of Destruction'),
('Garma Sword'),
('Garma Sword Oath'),
('Garnecia Elefantis'),
('Garoozis'),
('Garoth, Lightsworn Warrior'),
('Garuda the Wind Spirit'),
('Gate Guardian'),
('Gatekeeper'),
('Gateway of the Six'),
('Gateway to Dark World'),
('Gather Your Mind'),
('Gatling Dragon'),
('Gauntlet Warrior'),
('Gazelle the King of Mythical Beasts'),
('Gear Golem the Moving Fortress'),
('Gearfried the Iron Knight'),
('Gearfried the Swordmaster'),
('Geartown'),
('Gellenduo'),
('Gem Flash Energy'),
('Gemini Booster'),
('Gemini Counter'),
('Gemini Elf'),
('Gemini Imps'),
('Gemini Lancer'),
('Gemini Scorpion'),
('Gemini Soldier'),
('Gemini Spark'),
('Gemini Summoner'),
('Gemini Trap Hole'),
('Gene-Warped Warwolf'),
('Generation Shift'),
('Genetic Woman'),
('Germ Infection'),
('Gernia'),
('Get Your Game On!'),
('Getsu Fuhma'),
('Ghost Gardna'),
('Ghost Knight of Jackal'),
('Giant Axe Mummy'),
('Giant Flea'),
('Giant Germ'),
('Giant Kozaky'),
('Giant Orc'),
('Giant Rat'),
('Giant Red Seasnake'),
('Giant Soldier of Stone'),
('Giant Trap Hole'),
('Giant Trunade'),
('Giant Turtle Who Feeds on Flames'),
('Gift Card'),
('Gift of the Martyr'),
('Gift of The Mystical Elf'),
('Giga Gagagigo'),
('Giga-Tech Wolf'),
('Gigantes'),
('Gigantic Cephalotus'),
('Gigaplant  '),
('Gigastone Omega'),
('Gigobyte'),
('Gil Garth'),
('Gilasaurus'),
('Gilford the Legend'),
('Gilford the Lightning'),
('Giltia the D. Knight'),
('Girochin Kuwagata'),
('Give and Take'),
('Gladiator Beast Alexander'),
('Gladiator Beast Andal'),
('Gladiator Beast Bestiari'),
('Gladiator Beast Chariot'),
('Gladiator Beast Darius'),
('Gladiator Beast Dimacari'),
('Gladiator Beast Equeste'),
('Gladiator Beast Gaiodiaz'),
('Gladiator Beast Gyzarus'),
('Gladiator Beast Heraklinos'),
('Gladiator Beast Hoplomus'),
('Gladiator Beast Laquari'),
('Gladiator Beast Murmillo'),
('Gladiator Beast Octavius'),
('Gladiator Beast Retiari'),
('Gladiator Beast Samnite'),
('Gladiator Beast Secutor'),
('Gladiator Beast Spartacus'),
('Gladiator Beast Torax'),
('Gladiator Beast''s Battle Archfiend Shield'),
('Gladiator Beast''s Battle Gladius'),
('Gladiator Beast''s Battle Halberd'),
('Gladiator Beast''s Battle Manica'),
('Gladiator Beast''s Respite'),
('Gladiator Lash'),
('Gladiator Proving Ground'),
('Gladiator''s Return'),
('Glorious Illusion '),
('Goblin Attack Force'),
('Goblin Black Ops'),
('Goblin Calligrapher'),
('Goblin Decoy Squad'),
('Goblin Elite Attack Force'),
('Goblin Fan'),
('Goblin King'),
('Goblin of Greed'),
('Goblin out of the Frying Pan'),
('Goblin Out of the Frying Pan'),
('Goblin Recon Squad '),
('Goblin Thief'),
('Goblin Zombie'),
('Goblin''s Secret Remedy'),
('Goddess of Whim'),
('Goddess with the Third Eye'),
('Goe Goe the Gallant Ninja'),
('Goggle Golem'),
('Gogiga Gagagigo'),
('Goka, the Pyre of Malice'),
('Gokibore'),
('Gokipon'),
('Gold Sarcophagus'),
('Goldd, Wu-Lord of Dark World'),
('Goldd, Wu–Lord of Dark World'),
('Golden Bamboo Sword'),
('Golden Flying Fish'),
('Golden Homunculus'),
('Golden Ladybug'),
('Golem Sentry'),
('Gonogo'),
('Good Goblin Housekeeping'),
('Gora Turtle'),
('Gora Turtle of Illusion'),
('Gorgon''s Eye'),
('Gorz the Emissary of Darkness'),
('Gottoms'' Emergency Call'),
('Goyo Guardian'),
('Gozen Match'),
('Graceful Charity'),
('Graceful Dice'),
('Graceful Revival'),
('Gradius'),
('Gradius'' Option'),
('Gragonith, Lightsworn Dragon'),
('Granadora'),
('Grand Convergence'),
('Grand Tiki Elder'),
('Grandmaster of the Six Samurai'),
('Granmarg the Rock Monarch'),
('Grapple Blocker'),
('Grass Phantom'),
('Grasschopper'),
('Grave Lure'),
('Grave of the Super Ancient Organism'),
('Grave Ohja'),
('Grave Protector'),
('Grave Squirmer'),
('Gravedigger Ghoul'),
('Gravekeeper''s Assailant'),
('Gravekeeper''s Cannonholder'),
('Gravekeeper''s Chief'),
('Gravekeeper''s Commandant'),
('Gravekeeper''s Curse'),
('Gravekeeper''s Descendant'),
('Gravekeeper''s Guard'),
('Gravekeeper''s Priestess'),
('Gravekeeper''s Servant'),
('Gravekeeper''s Spear Soldier'),
('Gravekeeper''s Spy'),
('Gravekeeper''s Stele'),
('Gravekeeper''s Vassal'),
('Gravekeeper''s Visionary'),
('Gravekeeper''s Watcher'),
('Graverobber'),
('Graverobber''s Retribution'),
('Gravi-Crush Dragon'),
('Gravi–Crush Dragon'),
('Gravitic Orb'),
('Gravity Axe - Grarl'),
('Gravity Behemoth'),
('Gravity Bind'),
('Gray Wing'),
('Great Angus'),
('Great Dezard'),
('Great Long Nose'),
('Great Maju Garzett'),
('Great Moth'),
('Great Phantom Thief'),
('Great Shogun Shien'),
('Great Spirit'),
('Great White'),
('Greed'),
('Greed Grado'),
('Greed Quasar'),
('Green Baboon Defender of the Forest'),
('Green Baboon, Defender of the Forest'),
('Green Gadget'),
('Green Phantom King'),
('Greenkappa'),
('Gren Maju Da Eiza'),
('Gren, Tactician of Dark World'),
('Griggle'),
('Grinder Golem'),
('Ground Attacker Bugroth'),
('Ground Collapse'),
('Ground Spider'),
('Gryphon Wing'),
('Gryphon''s Feather Duster'),
('Guard Dog'),
('Guard Penalty'),
('Guardian Angel Joan'),
('Guardian Baou'),
('Guardian Ceal'),
('Guardian Eatos'),
('Guardian Elma'),
('Guardian Grarl'),
('Guardian Kay''est'),
('Guardian of Order'),
('Guardian of the Labyrinth'),
('Guardian of the Throne Room'),
('Guardian Sphinx'),
('Guardian Statue'),
('Guardian Tryce'),
('Gundari'),
('Gust'),
('Gust Fan'),
('Gyaku-Gire Panda'),
('Gyakutenno Megami'),
('Gyroid'),
('H - Heated Heart'),
('Hade-Hane'),
('Half or Nothing'),
('Hallowed Life Barrier'),
('Hamburger Recipe'),
('Hammer Shot'),
('Hamon, Lord of Striking Thunder'),
('Hand Destruction'),
('Hand of Nephthys'),
('Hand of the Six Samurai'),
('Handcuffs Dragon'),
('Hane-Hane'),
('Hanewata'),
('Haniwa'),
('Hannibal Necromancer'),
('Happy Lover'),
('Hard Armor'),
('Hard-sellin'' Goblin'),
('Hard-sellin'' Zombie'),
('Hardened Armed Dragon'),
('Harpie Girl'),
('Harpie Lady'),
('Harpie Lady 1'),
('Harpie Lady 2'),
('Harpie Lady 3'),
('Harpie Lady Sisters'),
('Harpie Queen'),
('Harpie''s Brother'),
('Harpie''s Feather Duster'),
('Harpie''s Pet Baby Dragon'),
('Harpie''s Pet Dragon'),
('Harpies'' Hunting Ground'),
('Harvest Angel of Wisdom'),
('Hate Buster'),
('Hayabusa Knight'),
('Headless Knight'),
('Healing Wave Generator'),
('Heart of Clear Water'),
('Heart of the Underdog'),
('Heavy Mech Support Platform'),
('Heavy Slump'),
('Heavy Storm'),
('Hecatrice'),
('Hedge Guard'),
('Helios - The Primordial Sun'),
('Helios – The Primordial Sun'),
('Helios Duo Megistus'),
('Helios Trice Megistus'),
('Helping Robo For Combat'),
('Helpoemer'),
('Herald of Creation'),
('Herald of Green Light'),
('Herald of Orange Light'),
('Herald of Purple Light'),
('Herculean Power'),
('Hercules Beetle'),
('Hero Barrier'),
('Hero Blast'),
('Hero Counterattack'),
('HERO Flash!!'),
('Hero Heart'),
('Hero Kid'),
('Hero Mask'),
('Hero Medal'),
('Hero Ring'),
('Hero Signal'),
('Hero Spirit'),
('Hero''s Bond'),
('Hero''s Rule 2'),
('Hibikime'),
('Hidden Armory'),
('Hidden Book of Spell'),
('Hidden Soldiers'),
('Hieracosphinx'),
('Hierocosphinx'),
('Hieroglyph Lithograph'),
('High Tide Gyojin'),
('Hiita the Fire Charmer'),
('Hino-Kagu-Tsuchi'),
('Hinotama'),
('Hinotama Soul'),
('Hiro''s Shadow Scout'),
('Hitotsu-Me Giant'),
('Homunculus the Alchemic Being'),
('Honest'),
('Honest (UTR)'),
('Horn of Heaven'),
('Horn of Light'),
('Horn of the Unicorn'),
('Horseytail'),
('Horus The Black Flame Dragon LV4'),
('Horus the Black Flame Dragon LV4'),
('Horus the Black Flame Dragon LV6'),
('Horus The Black Flame Dragon LV8'),
('Horus the Black Flame Dragon LV8'),
('Horus'' Servant'),
('Hoshiningen'),
('House of Adhesive Tape'),
('Howling Insect'),
('Huge Revolution'),
('Human-Wave Tactics'),
('Humanoid Slime'),
('Humanoid Worm Drake'),
('Hungry Burger'),
('Hunter Dragon'),
('Hunter Owl'),
('Hunter Spider'),
('Hunting Instinct'),
('Hydra Viper'),
('Hydro Pressure Cannon'),
('Hydrogeddon'),
('Hyena'),
('Hyosube'),
('Hyozanryu'),
('Hyper Hammerhead'),
('Hyper Psychic Blaster'),
('Hyper Psychic Blaster/Assault Mode'),
('Hyper Synchron'),
('Hysteric Fairy'),
('Hysteric Party'),
('Icarus Attack'),
('Ice Master'),
('Ice Queen'),
('Ido the Supreme Magical Force'),
('Il Blud'),
('Illusionist Faceless Mage'),
('Immortal Ruler'),
('Impenetrable Formation'),
('Imperial Custom'),
('Imperial Iron Wall'),
('Imperial Order'),
('Imprisoned Queen Archfiend'),
('Inaba White Rabbit'),
('Incandescent Ordeal'),
('Indomitable Fighter Lei Lei'),
('Indomitable Gladiator Beast'),
('Infernal Dragon'),
('Infernal Flame Emperor'),
('Infernal Incinerator'),
('Infernalqueen Archfiend'),
('Infernity Archfiend'),
('Infernity Beast'),
('Infernity Dwarf'),
('Infernity Force'),
('Infernity Guardian'),
('Infernity Necromancer'),
('Inferno'),
('Inferno Fire Blast'),
('Inferno Hammer'),
('Inferno Reckless Summon'),
('Inferno Tempest'),
('Infinite Cards'),
('Infinite Dismissal'),
('Infinity Dark'),
('Informer Spider'),
('Inherited Fortune'),
('Injection Fairy Lily'),
('Inmato'),
('Inpachi'),
('Insect Barrier'),
('Insect Imitation'),
('Insect Knight'),
('Insect Neglect'),
('Insect Princess'),
('Insect Queen'),
('Insect Soldiers of the Sky'),
('Inspection'),
('Instant Fusion'),
('Instant Neo Space'),
('Intercept'),
('Interdimensional Matter Transporter'),
('Interdimensional Warp'),
('Interplanetary Invader ''A'''),
('Introduction to Gallantry'),
('Invader of Darkness'),
('Invader of the Throne'),
('Invasion of Flames'),
('Inverse Universe'),
('Invigoration'),
('Invitation to a Dark Sleep'),
('Iris, the Earth Mother'),
('Iron Blacksmith Kotetsu'),
('Iron Chain Blaster'),
('Iron Chain Coil'),
('Iron Chain Dragon'),
('Iron Chain Repairman'),
('Iron Chain Snake'),
('Iron Core Armor'),
('Iron Core Immediate Disposal'),
('Iron Core Luster'),
('Iron Core of Koa''ki Meiru'),
('Iron Core Specimen Lab'),
('Island Turtle'),
('Ivy Shackles'),
('Izanagi'),
('Izanami'),
('Jack''s Knight'),
('Jade Insect Whistle'),
('Jade Knight'),
('Jain, Lightsworn Paladin'),
('Jam Breeding Machine'),
('Jam Defender'),
('Jar of Greed'),
('Jar Robber'),
('Javelin Beetle'),
('Javelin Beetle Pact'),
('Jelly Beans Man'),
('Jellyfish'),
('Jenis, Lightsworn Mender'),
('Jerry Beans Man'),
('Jester Confit'),
('Jester Lord'),
('Jetroid'),
('Jigen Bakudan'),
('Jinzo'),
('Jinzo - Lord'),
('Jinzo - Returner'),
('Jinzo #7'),
('Jirai Gumo'),
('Jowgen the Spiritualist'),
('Jowls of Dark Demise'),
('Judge Man'),
('Judgment Dragon'),
('Judgment of Anubis'),
('Judgment of the Desert'),
('Judgment of the Pharaoh'),
('Judgment of Thunder'),
('Junk Archer'),
('Junk Barrage'),
('Junk Box'),
('Junk Synchron'),
('Junk Warrior'),
('Jurassic World'),
('Just Desserts'),
('Justi-Break'),
('Jutte Fighter'),
('KA-2 Des Scissors'),
('Kabazauls'),
('Kagemusha of the Blue Flame'),
('Kahkki, Guerilla of Dark World'),
('Kaibaman'),
('Kaiser Colosseum'),
('Kaiser Dragon'),
('Kaiser Glider'),
('Kaiser Sea Horse'),
('Kaminari Attack'),
('Kaminote Blow'),
('Kangaroo Champ'),
('Karate Man'),
('Karbonala Warrior'),
('Karma Cut'),
('Kasha'),
('Kazejin'),
('Kelbek'),
('Keldo'),
('Kid Guard'),
('Killer Needle'),
('Kinetic Soldier'),
('King Dragun'),
('King Fog'),
('King of the Beasts'),
('King of the Skull Servants'),
('King of the Swamp'),
('King of Yamimakai'),
('King Pyron'),
('King Tiger Wanghu'),
('King''s Knight'),
('Kinka-Byo'),
('Kiryu'),
('Kiseitai'),
('Kishido Spirit'),
('Knight of the Red Lotus'),
('Knight''s Title'),
('Koa''ki Meiru Beetle'),
('Koa''ki Meiru Crusader'),
('Koa''ki Meiru Doom'),
('Koa''ki Meiru Drago'),
('Koa''ki Meiru Ghoulungulate'),
('Koa''ki Meiru Gravirose'),
('Koa''ki Meiru Guardian'),
('Koa''ki Meiru Hydro Barrier'),
('Koa''ki Meiru Ice'),
('Koa''ki Meiru Maximus'),
('Koa''ki Meiru Powerhand'),
('Koa''ki Meiru Rock'),
('Koa''ki Meiru Rooklord'),
('Koa''ki Meiru Sea Panther'),
('Koa''ki Meiru Speeder'),
('Koa''ki Meiru Tornado'),
('Koa''ki Meiru Urnight'),
('Koa''ki Meiru Valafar'),
('Koa''ki Meiru War Arms'),
('Koitsu'),
('Kojikocy'),
('Kotodama'),
('Koumori Dragon'),
('Kozaky'),
('Kozaky''s Self-Destruct Button'),
('Krebons'),
('Kryuel'),
('Kumootoko'),
('Kunai with Chain'),
('Kunoichi'),
('Kurama'),
('Kuraz the Light Monarch'),
('Kuriboh'),
('Kuribon'),
('Kuwagata'),
('Kwagar Hercules'),
('Kycoo the Ghost Destroyer'),
('La Jinn the Mystical Genie of the Lamp'),
('Labyrinth of Nightmare'),
('Labyrinth Tank'),
('Labyrinth Wall'),
('Lady Assailant of Flames'),
('Lady Ninja Yae'),
('Lady of Faith'),
('Lady Panther'),
('Larvae Moth'),
('Larvas'),
('Laser Cannon Armor'),
('Last Day of Witch'),
('Last Resort'),
('Last Turn'),
('Last Will'),
('Launcher Spider'),
('Lava Battleguard'),
('Lava Dragon'),
('Lava Golem'),
('Layard the Liberator'),
('Left Arm of the Forbidden One'),
('Left Leg of the Forbidden One'),
('Legacy Hunter'),
('Legacy of Yata-Garasu'),
('Legendary Black Belt'),
('Legendary Ebon Steed'),
('Legendary Flame Lord'),
('Legendary Jujitsu Master'),
('Legendary Sword'),
('Leghul'),
('Lekunga'),
('Leogun'),
('Lesser Dragon'),
('Lesser Fiend'),
('Level Conversion Lab'),
('Level Down!?'),
('Level Eater'),
('Level Limit - Area B'),
('Level Limit Area A'),
('Level Modulation'),
('Level Retuner'),
('Level Tuning'),
('Level Up!'),
('Level Warrior'),
('Levia-Dragon - Daedalus'),
('Leviadragon - Daedulus'),
('Liar Wire'),
('Lich Lord, King of the Underworld'),
('Life Absorbing Machine'),
('Life Equalizer'),
('Lifeforce Harmonizer'),
('Light and Darkness Dragon'),
('Light Barrier'),
('Light Effigy'),
('Light End Dragon'),
('Light Laser'),
('Light of Intervention'),
('Light of Judgment'),
('Light of Redemption'),
('Light Spiral'),
('Light-Imprisoning Mirror'),
('Lighten the Load'),
('Lightforce Sword'),
('Lightning Blade'),
('Lightning Conger'),
('Lightning Punisher'),
('Lightning Vortex'),
('Lightsworn Barrier'),
('Lightsworn Sabre'),
('Lightwave Tuning'),
('Limit Impulse'),
('Limit Reverse'),
('Limiter Overload'),
('Limiter Removal'),
('Lineage of Destruction'),
('Linear Accelerator Cannon'),
('Liquid Beast'),
('Little Chimera'),
('Little-Winguard'),
('Lizard Soldier'),
('Lone Wolf'),
('Lonefire Blossom'),
('Lord British Space Fighter'),
('Lord of D.'),
('Lord of the Lamp'),
('Lord Poison'),
('Lost Guardian'),
('Lucky Chance'),
('Lucky Cloud'),
('Lucky Iron Axe'),
('Lucky Pied Piper'),
('Lumina, Lightsworn Summoner'),
('Luminous Soldier'),
('Luminous Spark'),
('Luster Dragon'),
('Luster Dragon #2'),
('Lycanthrope'),
('Lyla, Lightsworn Sorceress'),
('M-Warrior #1'),
('M-Warrior #2'),
('Machina Armored Unit'),
('Machina Defender'),
('Machina Force'),
('Machina Fortress'),
('Machina Gearframe'),
('Machina Peacekeeper'),
('Machina Sniper'),
('Machina Soldier'),
('Machine Assembly Line'),
('Machine Conversion Factory'),
('Machine Duplication'),
('Machine King'),
('Machine King - B.C. 3000'),
('Machine King Prototype'),
('Machine Lord Ãœr'),
('Macro Cosmos'),
('Mad Archfiend'),
('Mad Dog of Darkness'),
('Mad Lobster'),
('Mad Reloader'),
('Mad Sword Beast'),
('Mage Power'),
('Magic Cylinder'),
('Magic Drain'),
('Magic Formula'),
('Magic Hole Golem'),
('Magic Jammer'),
('Magic Planter'),
('Magic Reflector'),
('Magical Android'),
('Magical Arm Shield'),
('Magical Blast'),
('Magical Citadel of Endymion'),
('Magical Dimension'),
('Magical Exemplar'),
('Magical Explosion'),
('Magical Ghost'),
('Magical Hats'),
('Magical Labyrinth'),
('Magical Mallet'),
('Magical Marionette'),
('Magical Merchant'),
('Magical Plant Mandragola'),
('Magical Reflect Slime'),
('Magical Scientist'),
('Magical Stone Excavation'),
('Magical Thorn'),
('Magicat'),
('Magician of Black Chaos'),
('Magician of Faith'),
('Magician''s Circle'),
('Magician''s Unite'),
('Magician''s Valkyria'),
('Magicians Unite'),
('Magna Drago'),
('Magna-Slash Dragon'),
('Magna–Slash Dragon'),
('Magnet Circle LV2'),
('Magnetic Mosquito'),
('Maha Vailo'),
('Maharaghi'),
('Maiden of Macabre'),
('Maiden of the Aqua'),
('Maiden of the Moonlight'),
('Majestic Dragon'),
('Majestic Mech - Goryu'),
('Majestic Mech - Ohka'),
('Majestic Mech - Senku'),
('Majestic Red Dragon'),
('Majestic Star Dragon'),
('Maji-Gire Panda'),
('Major Riot'),
('Maju Garzett'),
('Makiu, the Magical Mist'),
('Makyura the Destructor'),
('Malevolent Catastrophe'),
('Malevolent Mech – Goku En'),
('Malevolent Nuzzler'),
('Malfunction'),
('Malice Ascendant'),
('Malice Dispersion'),
('Malice Doll of Demise'),
('Mammoth Graveyard'),
('Man Beast of Ares'),
('Man Eater'),
('Man-Eater Bug'),
('Man-Eating Treasure Chest'),
('Man-Thro'' Tro'''),
('Manga Ryu-Ran'),
('Maniacal Servant'),
('Manju of the Ten Thousand Hands'),
('Manticore of Darkness'),
('Marauding Captain'),
('Marie the Fallen One'),
('Marionette Mite'),
('Mark of the Rose'),
('Marrionette Mite'),
('Marshmallon'),
('Marshmallon Glasses'),
('Maryokutai'),
('Masaki the Legendary Swordsman'),
('Mask of Brutality'),
('Mask of Darkness'),
('Mask of Dispel'),
('Mask of Restrict'),
('Mask of the Accursed'),
('Mask of Weakness'),
('Masked Chopper'),
('Masked Dragon'),
('Masked Sorcerer'),
('Mass Driver'),
('Mass Hypnosis'),
('Master & Expert'),
('Master Gig'),
('Master Kyonshee'),
('Master Monk'),
('Master of OZ'),
('Master of Oz'),
('Mataza the Zapper'),
('Mausoleum of the Emperor'),
('Max Warrior'),
('Maximum Six'),
('Mazera DeVille'),
('Mecha Bunny'),
('Mecha-Dog Marron'),
('Mechanical Hound'),
('Mechanical Snail'),
('Mechanicalchaser'),
('Meda Bat'),
('Medium Piece Golem'),
('Medusa Worm'),
('Mefist the Infernal General'),
('Mega Thunderball'),
('Mega Ton Magical Cannon'),
('Megamorph'),
('Megarock Dragon'),
('Megasonic Eye'),
('Mei-kou, Master of Barriers'),
('Mei–Kou, Master of Barriers'),
('Melchid the Four-Face Beast'),
('Meltiel Sage of the Sky'),
('Meltiel, Sage of the Sky'),
('Memory Crusher'),
('Mermaid Archer'),
('Mermaid Knight'),
('Mesmeric Control'),
('Messenger of Peace'),
('Metabo-Shark'),
('Metal Armored Bug'),
('Metal Detector'),
('Metal Dragon'),
('Metal Fish'),
('Metal Guardian'),
('Metal Reflect Slime'),
('Metal Shooter'),
('Metallizing Parasite - Lunatite'),
('Metalmorph'),
('Metalsilver Armor'),
('Metalzoa'),
('Metamorphosis'),
('Metaphysical Regeneration'),
('Meteor Dragon'),
('Meteor Flare'),
('Meteor of Destruction'),
('Meteorain'),
('Mezuki'),
('Michizure'),
('Micro Ray'),
('Mid Shield Gardna'),
('Mighty Guard'),
('Mikazukinoyaiba'),
('Millenium Scorpion'),
('Millennium Golem'),
('Millennium Scorpion'),
('Millennium Shield'),
('Milus Radiant'),
('Minar'),
('Mind Control'),
('Mind Crush'),
('Mind Haxorz'),
('Mind Master'),
('Mind on Air'),
('Mind Over Matter'),
('Mind Protector'),
('Mind Trust'),
('Mind Wipe'),
('Mine Golem'),
('Minefield Eruption'),
('Minefieldriller'),
('Miniaturize'),
('Minoan Centaur'),
('Minor Goblin Official'),
('Miracle Dig'),
('Miracle Fertilizer'),
('Miracle Flipper'),
('Miracle Fusion'),
('Miracle Jurassic Egg'),
('Miracle Kids'),
('Miracle Locus'),
('Miracle Restoring'),
('Miraculous Descent'),
('Miraculous Rebirth'),
('Mirage Dragon'),
('Mirage Knight'),
('Mirage of Nightmare'),
('Mirage Tube'),
('Mirror Force'),
('Mirror Gate'),
('Mirror of Oaths'),
('Mirror of Yata'),
('Mirror Wall'),
('Misairuzame'),
('Misfortune'),
('Mispolymerization'),
('Mist Archfiend'),
('Mist Body'),
('Mist Valley Shaman'),
('Mist Valley Soldier'),
('Mist Valley Thunderbird'),
('Mist Wurm'),
('Moai Interceptor Cannon'),
('Moai Interceptor Cannons'),
('Mobius the Frost Monarch'),
('Moisture Creature'),
('Moja'),
('Mokey Mokey'),
('Mokey Mokey King'),
('Mokey Mokey Smackdown'),
('Molten Behemoth'),
('Molten Destruction'),
('Molten Zombie'),
('Molting Escape'),
('Monk Fighter'),
('Monster Egg'),
('Monster Gate'),
('Monster Reborn'),
('Monster Recovery'),
('Monster Reincarnation'),
('Montage Dragon'),
('Moon Dragon Quilla'),
('Moon Envoy'),
('Morale Boost'),
('Moray of Greed'),
('Morinphen'),
('Mormolith'),
('Morphing Jar'),
('Morphing Jar #2'),
('Morphtransition'),
('Morphtronic Accelerator'),
('Morphtronic Bind'),
('Morphtronic Boarden'),
('Morphtronic Boomboxen'),
('Morphtronic Cameran'),
('Morphtronic Celfon'),
('Morphtronic Clocken'),
('Morphtronic Cord'),
('Morphtronic Datatron'),
('Morphtronic Engine'),
('Morphtronic Forcefield'),
('Morphtronic Magnen'),
('Morphtronic Magnen Bar'),
('Morphtronic Map'),
('Morphtronic Mix-up'),
('Morphtronic Monitron'),
('Morphtronic Radion'),
('Morphtronic Remoten'),
('Morphtronic Repair Unit'),
('Morphtronic Rusty Engine'),
('Morphtronic Scopen'),
('Morphtronic Slingen'),
('Morphtronic Videon'),
('Mosaic Manticore'),
('Mother Grizzly'),
('Mother Spider'),
('Mountain'),
('Mr. Volcano'),
('Mucus Yolk'),
('Mudora'),
('Muka Muka'),
('Multiple Piece Golem'),
('Multiplication of Ants'),
('Multiply'),
('Mushroom Man'),
('Mushroom Man #2'),
('Musician King'),
('Mustering of the Dark Scorpions'),
('My Body as a Shield'),
('Mysterious Guard'),
('Mysterious Puppeteer'),
('Mysterious Triangle'),
('Mystic Box'),
('Mystic Clown'),
('Mystic Horseman'),
('Mystic Lamp'),
('Mystic Plasma Zone'),
('Mystic Probe'),
('Mystic Swordsman LV2'),
('Mystic Swordsman LV4'),
('Mystic Swordsman LV6'),
('Mystic Tomato'),
('Mystical Cards of Light'),
('Mystical Elf'),
('Mystical Knight of Jackal'),
('Mystical Moon'),
('Mystical Sheep #1'),
('Mystical Sheep #2'),
('Mystical Shine Ball'),
('Mystical Space Typhoon'),
('Mystical Wind Typhoon'),
('Mystik Wok'),
('Mythical Beast Cerberus'),
('Nanobreaker'),
('Narrow Pass'),
('Natural Disaster'),
('Natural Tune'),
('Nature''s Reflection'),
('Necklace of Command'),
('Necro Gardna'),
('Necroface'),
('Necrolancer the Timelord'),
('Necrovalley'),
('Needle Burrower'),
('Needle Ceiling'),
('Needle Wall'),
('Needle Worm'),
('Needlebug Nest'),
('Nega-Ton Corepanel'),
('Negate Attack'),
('Neko Mane King'),
('Nekogal #1'),
('Nekogal #2'),
('Nemuriko'),
('Neo Aqua Madoor'),
('Neo Bug'),
('Neo Space'),
('Neo Space Pathfinder'),
('Neo the Magic Swordsman'),
('Neo-Parshath, The Sky Paladin'),
('Neo-Spacian Air Hummingbird'),
('Neo-Spacian Aqua Dolphin'),
('Neo-Spacian Dark Panther'),
('Neo-Spacian Flare Scarab'),
('Neo-Spacian Glow Moss'),
('Neo-Spacian Grand Mole'),
('Neo-Spacian Marine Dolphin'),
('Neo-Spacian Twinkle Moss'),
('Neo–Spacian Air Hummingbird'),
('Neo–Spacian Glow Moss'),
('Neo–Spacian Grand Mole'),
('Neos Force'),
('Neos Wiseman'),
('Nettles'),
('Newdoria'),
('NEX'),
('Next to be Lost'),
('Night Assailant'),
('Night Wing Sorceress'),
('Night''s End Sorcerer'),
('Nightmare Archfiends'),
('Nightmare Horse'),
('Nightmare Penguin'),
('Nightmare Wheel'),
('Nightmare''s Steelcage'),
('Nimble Momonga'),
('Nimble Musasabi'),
('Nin-Ken Dog'),
('Ninja Grandmaster Sasuke'),
('Ninjitsu Art of Decoy'),
('Ninjitsu Art of Transformation'),
('Nitro Synchron'),
('Nitro Unit'),
('Nitro Warrior'),
('Niwatori'),
('No Entry!'),
('Nobleman of Crossout'),
('Nobleman of Extermination'),
('Nobleman-Eater Bug'),
('Noisy Gnat'),
('Non Aggression Area'),
('Non-Fusion Area'),
('Non-Spellcasting Area'),
('Non–Spellcasting Area'),
('Nova Summoner'),
('Novox''s Prayer'),
('Nubian Guard'),
('Null and Void'),
('Numinous Healer'),
('Nurse Reficule the Fallen One'),
('Nutrient Z'),
('Nuvia the Wicked'),
('O - Oversoul'),
('Obelisk the Tormentor'),
('Obnoxious Celtic Guard'),
('Obnoxious Celtic Guardian'),
('Obsidian Dragon'),
('Ocean Dragon Lord - Neo Daedalus'),
('Ocean''s Keeper'),
('Octoberser'),
('Ocubeam'),
('Offering to the Immortals'),
('Offering to the Snake Deity'),
('Offerings to the Doomed'),
('Ogre of the Black Shadow'),
('Ogre of the Scarlet Sorrow'),
('Oilmen'),
('Ojama Black'),
('Ojama Blue'),
('Ojama Country'),
('Ojama Delta Hurricane!!'),
('Ojama Green'),
('Ojama King'),
('OJAMA KING'),
('Ojama Knight'),
('Ojama Red'),
('Ojama Trio'),
('Ojama Yellow'),
('Ojamagic'),
('Ojamuscle'),
('Old Vindictive Magician'),
('Omega Goggles'),
('Ominous Fortunetelling'),
('One for One'),
('One-Eyed Shield Dragon'),
('Oni Tank T-34'),
('Ooguchi'),
('Ookazi'),
('Oppressed People'),
('Opti-Camouflage Armor'),
('Opticlops'),
('Option Hunter'),
('Oracle of the Sun'),
('Orb of Yasaka'),
('Orbital Bombardment'),
('Orca Mega-Fortress of Darkness'),
('Ordeal of a Traveler'),
('Order to Charge'),
('Order to Smash'),
('Oscillo Hero'),
('Oscillo Hero #2'),
('Oshaleon'),
('Otherworld - The ''''A'''' Zone'),
('Otohime'),
('Outstanding Dog Marron'),
('Over Destiny'),
('Over Limit'),
('Overdoom Line'),
('Overdrive'),
('Overdrive Teleporter'),
('Overload Fusion'),
('Overwhelm'),
('Overworked'),
('Owner''s Seal'),
('Oxygeddon'),
('Oyster Meister'),
('Painful Choice'),
('Paladin of the Cursed Dragon'),
('Paladin of White Dragon'),
('Pale Beast'),
('Pandaborg'),
('Pandemonium'),
('Pandemonium Watchbear'),
('Panther Warrior'),
('Paralyzing Chain'),
('Paralyzing Potion'),
('Parasite Paracide'),
('Parasitic Ticky'),
('Parrot Dragon'),
('Parry'),
('Patrician of Darkness'),
('Patroid'),
('Patrol Robo'),
('Peacock'),
('Penalty Game!'),
('Penguin Knight'),
('Penguin Soldier'),
('Penumbral Soldier Lady'),
('People Running About'),
('Perfect Machine King'),
('Perfectly Ultimate Great Moth'),
('Performance of Sword'),
('Peten the Dark Clown'),
('Petit Angel'),
('Petit Dragon'),
('Petit Moth'),
('Phalanx Pike'),
('Phantasmal Martyrs'),
('Phantom Beast Cross-Wing'),
('Phantom Beast Rock-Lizard'),
('Phantom Beast Thunder-Pegasus'),
('Phantom Beast Wild-Horn'),
('Phantom Cricket'),
('Phantom Dragon'),
('Phantom Dragonray Bronto'),
('Phantom of Chaos'),
('Phantom Skyblaster'),
('Pharaoh''s Servant'),
('Pharaoh''s Treasure'),
('Pharaonic Protector'),
('Phoenix Gearfried'),
('Phoenix Wing Wind Blast'),
('Phoenixian Cluster Amaryllis'),
('Phoenixian Seed'),
('Photon Generator Unit'),
('Physical Double'),
('Pigeonholing Books of Spell'),
('Pikeru''s Circle of Enchantment'),
('Pikeru''s Second Sight'),
('Pinch Hopper'),
('Pineapple Blast'),
('Piranha Army'),
('Pitch-Black Power Stone'),
('Pitch-Black Warwolf'),
('Pitch-Dark Dragon'),
('Pitch–Black Power Stone'),
('Pixie Knight'),
('Pixie Ring'),
('Plague Wolf'),
('Plaguespreader Zombie'),
('Planet Pollutant Virus'),
('Plant Food Chain'),
('Poison Chain'),
('Poison Draw Frog'),
('Poison Fangs'),
('Poison Mummy'),
('Poison of the Old Man'),
('Pole Position'),
('Pollinosis'),
('Polymerization'),
('Portable Battery Pack'),
('Possessed Dark Soul'),
('Pot of Avarice'),
('Pot of Benevolence'),
('Pot of Generosity'),
('Pot of Greed'),
('Power Bond'),
('Power Capsule'),
('Power Filter'),
('Power Injector'),
('Power Invader'),
('Power of Kaishin'),
('Power Pickaxe'),
('Power Supplier'),
('Power Tool Dragon'),
('Powered Tuner'),
('Pragtical'),
('Precious Cards from Beyond'),
('Premature Burial'),
('Preparation of Rites'),
('Prepare to Strike Back'),
('Prevent Rat'),
('Prevention Star'),
('Prickle Fairy'),
('Pride of the Weak'),
('Prideful Roar'),
('Primal Seed'),
('Prime Material Dragon'),
('Prime Material Falcon'),
('Princess Curran'),
('Princess of Tsurugi'),
('Princess Pikeru'),
('Prisman'),
('Prohibition'),
('Prometheus, King of the Shadows'),
('Proof of Powerlessness'),
('Protective Soul Ailin'),
('Protector of the Sanctuary'),
('Protector of the Throne'),
('Proto-Cyber Dragon'),
('Pseudo Space'),
('Psi-Curse'),
('Psi-Impulse'),
('Psi-Station'),
('Psychic Commander'),
('Psychic Emperor'),
('Psychic Jumper'),
('Psychic Kappa'),
('Psychic Lifetrancer'),
('Psychic Overload'),
('Psychic Path'),
('Psychic Rejuvenation'),
('Psychic Snail'),
('Psychic Soul'),
('Psychic Sword'),
('Psychic Trigger'),
('Psychic Tuning'),
('Psychokinesis'),
('Pulling the Rug'),
('Pumpking the King of Ghosts'),
('Punished Eagle'),
('Puppet King'),
('Puppet Master'),
('Puppet Plant'),
('Pursuit Chaser'),
('Pyramid Energy'),
('Pyramid of Light'),
('Pyramid Turtle'),
('Pyro Clock of Destiny'),
('Queen Bird'),
('Queen of Autumn Leaves'),
('Queen of Thorns'),
('Queen''s Bodyguard'),
('Queen''s Double'),
('Queen''s Knight'),
('Question'),
('Quick Charger'),
('Quickdraw Synchron'),
('Quillbolt Hedgehog'),
('R - Righteous Justice'),
('Rabid Horseman'),
('Radiant Mirror Force'),
('Radiant Spirit'),
('Rafflesia Seduction'),
('Raging Cloudian'),
('Raging Earth'),
('Raging Eria'),
('Raging Flame Sprite'),
('Raging Mad Plants'),
('Rai-Jin'),
('Rai-Mei'),
('Raigeki'),
('Raigeki Break'),
('Raimei'),
('Rain of Mercy'),
('Rain Storm'),
('Rainbow Dark Dragon'),
('Rainbow Dragon'),
('Rainbow Flower'),
('Rainbow Gravity'),
('Rainbow Life'),
('Rainbow Neos'),
('Rainbow Path'),
('Rainbow Veil'),
('Raise Body Heat'),
('Raiza the Storm Monarch'),
('Rallis the Star Bird'),
('Rampaging Rhynos'),
('Rapid-Fire Magician'),
('Raptor Wing Strike'),
('Rare Metal Dragon'),
('Rare Metalmorph'),
('Rare Value'),
('Raregold Armor'),
('Raviel, Lord of Phantasms'),
('Ray & Temperature'),
('Ray of Hope'),
('Razor Lizard'),
('Re-Fusion'),
('Ready for Intercepting'),
('Really Eternal Rest'),
('Realm of Light'),
('Reaper of the Cards'),
('Reaper on the Nightmare'),
('Reasoning'),
('Reborn Zombie'),
('Reckless Greed'),
('Reckoned Power'),
('Recurring Nightmare'),
('Recycle'),
('Recycling Batteries'),
('Red Archery Girl'),
('Red Dragon Archfiend'),
('Red Dragon Archfiend/Assault Mode'),
('Red Gadget'),
('Red Medicine'),
('Red Ogre'),
('Red-Eyes B. Chick'),
('Red-Eyes B. Dragon'),
('Red-Eyes Black Metal Dragon'),
('Red-Eyes Darkness Dragon'),
('Red-Eyes Darkness Metal Dragon'),
('Red-Eyes Wyvern'),
('Red-Moon Baby'),
('Red–Eyes Zombie Dragon'),
('Reflect Bounder'),
('Regenerating Mummy'),
('Regenerating Rose'),
('Regulus'),
('Reign-Beaux, Overlord of Dark World'),
('Reinforce Truth'),
('Reinforced Human Psychic Borg'),
('Reinforcement of the Army'),
('Reinforcements'),
('Rekindling'),
('Release from Stone'),
('Release Restraint'),
('Release Restraint Wave'),
('Relieve Monster'),
('Relinquished'),
('Relinquished Spider'),
('Reload'),
('Remote Revenge'),
('Remove Brainwashing'),
('Remove Trap'),
('Renge, Gatekeeper of Dark World'),
('Reptilianne Gardna'),
('Reptilianne Gorgon'),
('Reptilianne Hydra'),
('Reptilianne Medusa'),
('Reptilianne Naga'),
('Reptilianne Poison'),
('Reptilianne Rage'),
('Reptilianne Scylla'),
('Reptilianne Servant'),
('Reptilianne Spawn'),
('Reptilianne Vaskii'),
('Reptilianne Viper'),
('Rescue Cat'),
('Rescueroid'),
('Reshef the Dark Being'),
('Respect Play'),
('Restructer Revolution'),
('Return from the Different Dimension'),
('Return of the Doomed'),
('Return of the Six Samurai'),
('Return Soul'),
('Return Zombie'),
('Reversal of Fate'),
('Reversal Quiz'),
('Reverse of Neos'),
('Reverse Trap'),
('Revival Gift'),
('Revival Jam'),
('Revival of Dokurorider'),
('Revival of the Immortals'),
('Revived King Ha Des'),
('Revoke Fusion'),
('Ribbon of Rebirth'),
('Right Arm of the Forbidden One'),
('Right Leg of the Forbidden One'),
('Rigorous Reaver'),
('Ring of Defense'),
('Ring of Destruction'),
('Ring of Magnetism'),
('Rinyan, Lightsworn Rogue'),
('Riryoku'),
('Riryoku Field'),
('Rise of the Snake Deity'),
('Rising Air Current'),
('Rising Energy'),
('Rite of Spirit'),
('Ritual Buster'),
('Ritual Cage'),
('Ritual Foregone'),
('Ritual of Destruction'),
('Ritual of Grace'),
('Ritual Raven'),
('Ritual Sealing'),
('Ritual Weapon'),
('Rivalry of Warlords'),
('Road Synchron'),
('Road Warrior'),
('Roar of the Earthbound'),
('Roaring Ocean Snake'),
('Robbin'' Goblin'),
('Robbin'' Zombie'),
('Robolady'),
('Robotic Knight'),
('Roboyarou'),
('Roc from the Valley of Haze'),
('Rock Bombardment'),
('Rock Ogre Grotto #1'),
('Rocket Jumper'),
('Rocket Pilder'),
('Rocket Warrior'),
('Rockstone Warrior'),
('Rod of Silence - Kay''est'),
('Rod of the Mind''s Eye'),
('Rogue Doll'),
('Roll Out!'),
('Root Water'),
('Rope of Life'),
('Rose Bud'),
('Rose Fairy'),
('Rose Tentacles'),
('Rose, Warrior of Revenge'),
('Roulette Barrel'),
('Royal Command'),
('Royal Decree'),
('Royal Firestorm Guards'),
('Royal Keeper'),
('Royal Knight'),
('Royal Magical Library'),
('Royal Oppression'),
('Royal Surrender'),
('Royal Swamp Eel'),
('Royal Tribute'),
('Royal Writ of Taxation'),
('Rude Kaiser'),
('Ruin, Queen of Oblivion'),
('Rush Recklessly'),
('Ruthless Denial'),
('Ryko, Lightsworn Hunter'),
('Ryu Kokki'),
('Ryu Senshi'),
('Ryu-Kishin'),
('Ryu-Kishin Clown'),
('Ryu-Kishin Powered'),
('Ryu-Ran'),
('Saber Beetle'),
('Saber Hole'),
('Saber Slash'),
('Sabersaurus'),
('Sacred Crane'),
('Sacred Phoenix of Nephthys'),
('Sage of Silence'),
('Sage of Stillness'),
('Sage''s Stone'),
('Saggi the Dark Clown'),
('Sakuretsu Armor'),
('Salamandra'),
('Salvage'),
('Samsara'),
('Samsara Kaiser'),
('Samsara Lotus'),
('Sand Gambler'),
('Sand Moth'),
('Sand Stone'),
('Sanga of the Thunder'),
('Sangan'),
('Sanguine Swamp'),
('Sanwitch'),
('Sasuke Samurai'),
('Sasuke Samurai #2'),
('Sasuke Samurai #3'),
('Sasuke Samurai #4'),
('Satellite Cannon'),
('Sauropod Brachion'),
('Savage Colosseum'),
('Scanner'),
('Scapegoat'),
('Scarr, Scout of Dark World'),
('Scary Moth'),
('Science Soldier'),
('Scrap Recycler'),
('Scrap-Iron Scarecrow'),
('Scroll of Bewitchment'),
('Scrubbed Raid'),
('Sea Dragon Lord Gishilnodon'),
('Sea Koala'),
('Sea Serpent Warrior of Darkness'),
('Seal of the Ancients'),
('Seal of Wickedness'),
('Sealmaster Meisei'),
('Search Striker'),
('Searchlightman'),
('Sebek''s Blessing'),
('Second Coin Toss'),
('Second Goblin'),
('Secret Barrel'),
('Secret Pass to the Treasures'),
('Secret Village of the Spellcasters'),
('Secrets of the Gallant'),
('Sectarian of Secrets'),
('Security Orb'),
('Seed Cannon'),
('Seed of Deception'),
('Seed of Flame'),
('Seismic Crasher'),
('Seismic Shockwave'),
('Seiyaryu'),
('Self-Destruct Button'),
('Senet Switch'),
('Sengenjin'),
('Senju of the Thousand Hands'),
('Senri Eye'),
('Sentinel of the Seas'),
('Serial Spell'),
('Serpent Night Dragon'),
('Serpent Suppression'),
('Serpentine Princess'),
('Servant of Catabolism'),
('Seven Tools of the Bandit'),
('Shadow Delver'),
('Shadow Ghoul'),
('Shadow of Eyes'),
('Shadow Spell'),
('Shadow Tamer'),
('Shadow-Imprisoning Mirror'),
('Shadowknight Archfiend'),
('Shadowpriestess of Ohm'),
('Shadowslayer'),
('Shapesnatch'),
('Share the Pain'),
('Shark Cruiser'),
('Shattered Axe'),
('Shield & Sword'),
('Shield Crush'),
('Shield Spear'),
('Shield Warrior'),
('Shield Wing'),
('Shield Worm'),
('Shien''s Castle of Mist'),
('Shien''s Footsoldier'),
('Shien''s Spy'),
('Shift'),
('Shifting Shadows'),
('Shinato, King of a Higher Plane'),
('Shinato''s Ark'),
('Shine Palace'),
('Shining Abyss'),
('Shining Angel'),
('Shining Friendship'),
('Shining Silver Force'),
('Shiny Black C'),
('Shire, Lightsworn Spirit'),
('Shooting Star Bow - Ceal'),
('Short Circuit'),
('Shovel Crusher'),
('Shreddder'),
('Shrink'),
('Shutendoji'),
('Silent Abyss'),
('Silent Doom'),
('Silent Insect'),
('Silent Magician LV4'),
('Silent Magician LV8'),
('Silent Strider'),
('Silent Swordsman LV3'),
('Silent Swordsman LV5'),
('Silent Swordsman LV7'),
('Sillva, Warlord of Dark World'),
('Silpheed'),
('Silver Bow and Arrow'),
('Silver Fang'),
('Silver Wing'),
('Simorgh, Bird of Ancestry  '),
('Simorgh, Bird of Divinity'),
('Simultaneous Loss'),
('Sinister Seeds'),
('Sinister Serpent'),
('Sinister Sprocket'),
('Six Samurai United'),
('Six Scrolls of the Samurai'),
('Skelengel'),
('Skill Drain'),
('Skill Successor'),
('Skilled Dark Magician'),
('Skilled White Magician'),
('Skreech'),
('Skull Archfiend of Lightning'),
('Skull Conductor'),
('Skull Dice'),
('Skull Dog Marron'),
('Skull Guardian'),
('Skull Invitation'),
('Skull Knight'),
('Skull Knight #2'),
('Skull Lair'),
('Skull Mariner'),
('Skull Red Bird'),
('Skull Servant'),
('Skull-Mark Ladybug'),
('Sky Dragon'),
('Sky Scourge Enrise'),
('Sky Scourge Invicil'),
('Sky Scourge Norleras'),
('Skyscraper'),
('Skyscraper 2 - Hero City'),
('Skyscraper 2 – Hero City'),
('Slate Warrior'),
('Sleeping Lion'),
('Slifer the Sky Dragon'),
('Slip of Fortune'),
('Slip Summon'),
('Slot Machine'),
('Small Piece Golem'),
('Smashing Ground'),
('Smoke Grenade of the Thief'),
('Snake Deity''s Command'),
('Snake Fang'),
('Snake Rain'),
('Snake Whistle'),
('Snatch Steal'),
('Snipe Hunter'),
('Snowman Eater'),
('Sogen'),
('Soitsu'),
('Solar Flare Dragon'),
('Solar Ray'),
('Solar Recharge'),
('Solemn Judgment'),
('Solemn Wishes'),
('Solidarity'),
('Solitaire Magician'),
('Solomon''s Lawbook'),
('Sonic Bird'),
('Sonic Chick'),
('Sonic Duck'),
('Sonic Jammer'),
('Sonic Maid'),
('Sonic Shooter'),
('Sorcerer of Dark Magic'),
('Sorcerer of the Doomed'),
('Soul Absorbing Bone Tower'),
('Soul Absorption'),
('Soul Demolition'),
('Soul Devouring Bamboo Sword'),
('Soul Exchange'),
('Soul of Fire'),
('Soul of Purity and Light'),
('Soul of the Pure'),
('Soul Release'),
('Soul Resurrection'),
('Soul Reversal'),
('Soul Rope'),
('Soul Taker'),
('Soul Tiger'),
('Soul-Absorbing Bone Tower'),
('Souleater'),
('Souls of the Forgotten'),
('Space Gift'),
('Space Mambo'),
('Space Manbow'),
('Spacegate'),
('Spark Blaster'),
('Sparks'),
('Spatial Collapse'),
('Spear Cretin'),
('Spear Dragon'),
('Special Hurricane'),
('Speed Warrior'),
('Spell Absorption'),
('Spell Calling'),
('Spell Canceller'),
('Spell Chronicle'),
('Spell Economics'),
('Spell Gear'),
('Spell of Pain'),
('Spell Power Grasp'),
('Spell Purification'),
('Spell Reactor - RE'),
('Spell Reclamation'),
('Spell Reproduction'),
('Spell Shattering Arrow'),
('Spell Shield Type-8'),
('Spell Shield Type–8'),
('Spell Striker'),
('Spell Vanishing'),
('Spell-Stopping Statue'),
('Spell-Stopping Statute'),
('Spellbinding Circle'),
('Sphere of Chaos'),
('Spherous Lady'),
('Sphinx Teleia'),
('Spider Egg'),
('Spider Web'),
('Spider''s Lair'),
('Spike Seadra'),
('Spikebot'),
('Spined Gillman'),
('Spiral Serpent'),
('Spiral Spear Strike'),
('Spirit Barrier'),
('Spirit Burner'),
('Spirit Caller'),
('Spirit Elimination'),
('Spirit Force'),
('Spirit Message ""A""'),
('Spirit Message ""I""'),
('Spirit Message ""L""'),
('Spirit Message ""N""'),
('Spirit Message A'),
('Spirit Message I'),
('Spirit Message L'),
('Spirit Message N'),
('Spirit of Flames'),
('Spirit of the Books'),
('Spirit of the Breeze'),
('Spirit of the Harp'),
('Spirit of the Jar of Greed'),
('Spirit of the Pharaoh'),
('Spirit of the Pot of Greed'),
('Spirit of the Six Samurai'),
('Spirit Reaper'),
('Spirit Ryu'),
('Spirit''s Invitation'),
('Spiritual Earth Art - Kurogane'),
('Spiritual Energy Settle Machine'),
('Spiritual Fire Art - Kurenai'),
('Spiritual Forest'),
('Spiritual Water Art - Aoi'),
('Spiritual Wind Art - Miyabi'),
('Spiritualism'),
('Splendid Venus'),
('Spring of Rebirth'),
('Spyder Spider'),
('St. Joan'),
('Stamping Destruction'),
('Star Blast'),
('Star Boy'),
('Stardust Dragon'),
('Stardust Dragon Assault Mode'),
('Stardust Dragon/Assault Mode'),
('Stardust Xiaolong'),
('Statue of the Wicked'),
('Staunch Defender'),
('Stealth Bird'),
('Stealthroid'),
('Steam Gyroid'),
('Steamroid'),
('Steel Ogre Grotto #1'),
('Steel Ogre Grotto #2'),
('Steel Scorpion'),
('Steel Shell'),
('Stim-Pack'),
('Stone Dragon'),
('Stone Ogre Grotto'),
('Stone Statue of the Aztecs'),
('Stop Defense'),
('Storm Caller'),
('Storm Shooter'),
('Storming Wynn'),
('Straight Flush'),
('Stray Asmodian'),
('Stray Lambs'),
('Strike Ninja'),
('Strike Slash'),
('Strong Wind Dragon'),
('Stronghold the Moving Fortress'),
('Stuffed Animal'),
('Stumbling'),
('Stygian Dirge'),
('Submarine Frog'),
('Submarineroid'),
('Substitoad'),
('Success Probability 0%'),
('Succubus Knight'),
('Suijin'),
('Summon Cloud'),
('Summon Limit'),
('Summon Reactor - SK'),
('Summoned Skull'),
('Summoner Monk'),
('Summoner of Illusions'),
('Summoner''s Art'),
('Sun Dragon Inti'),
('Sunlight Unicorn'),
('Sunny Pixie'),
('Supay'),
('Super Conductor Tyranno'),
('Super Double Summon'),
('Super Junior Confrontation'),
('Super Polymerization'),
('Super Rejuvenation'),
('Super Robolady'),
('Super Roboyarou'),
('Super Solar Nutrient'),
('Super Vehicroid - Stealth Union'),
('Super Vehicroid Jumbo Drill'),
('Super War-Lion'),
('Super-Ancient Dinobeast'),
('Super-Electromagnetic Voltech Dragon'),
('Super-Nimble Mega Hamster'),
('Superalloy Beast Raptinus'),
('Superancient Deepsea King Coelacanth'),
('Superancient Deepsea King Coelacanth '),
('Supercharge'),
('Supervise'),
('Supply'),
('Supremacy Berry'),
('Survival Instinct'),
('Susa Soldier'),
('Swallow Flip'),
('Swallow''s Nest'),
('Swamp Battleguard'),
('Swap Frog'),
('Swarm of Locusts'),
('Swarm of Scarabs'),
('Swift Birdman Joe'),
('Swift Gaia the Fierce Knight'),
('Swift Samurai Storm!'),
('Swiftstrike Armor'),
('Swing of Memories'),
('Sword Hunter'),
('Sword Master'),
('Sword of Dark Destruction'),
('Sword of Dark Rites'),
('Sword of Deep-Seated'),
('Sword of Dragon''s Soul'),
('Sword of Kusanagi'),
('Sword of Sparkles'),
('Sword of the Soul-Eater'),
('Swords of Concealing Light'),
('Swords of Revealing Light'),
('Swordsman of Landstar'),
('Swordstalker'),
('Symbol of Heritage'),
('Symbols of Duty'),
('Synchro Barrier'),
('Synchro Blast Wave'),
('Synchro Boost'),
('Synchro Change'),
('Synchro Control'),
('Synchro Deflector'),
('Synchro Strike'),
('Synchronized Realm'),
('Synthesis Spell'),
('Synthetic Seraphim'),
('System Down'),
('T.A.D.P.O.L.E.'),
('Tactical Espionage Expert'),
('Tail Swipe'),
('Tailor of the Fickle'),
('Tainted Wisdom'),
('Takriminos'),
('Takuhee'),
('Talisman of Spell Sealing'),
('Talisman of Trap Sealing'),
('Taunt'),
('Telekinetic Charging Cell'),
('Telekinetic Power Wall'),
('Telekinetic Shocker'),
('Telepathic Power'),
('Teleport'),
('Tempest Magician'),
('Temple of Skulls'),
('Temple of the Sun'),
('Tenkabito Shien'),
('Terra Firma Gravity'),
('Terra the Terrible'),
('Terraforming'),
('Terrible Deal'),
('Terrorking Archfiend'),
('Terrorking Salmon'),
('Test Ape'),
('Test Tiger'),
('Testament of the Arcane Lords'),
('Tethys the Goddess of Light'),
('Teva'),
('The 13th Grave'),
('The A. Forces'),
('The Agent of Creation - Venus'),
('The Agent of Force - Mars'),
('The Agent of Judgement - Saturn'),
('The Agent of Judgment - Saturn'),
('The Agent of Wisdom - Mercury'),
('The All-Seeing White Tiger'),
('The Beginning of the End'),
('The Big March of Animals'),
('The Big Saturn'),
('The Bistro Butcher'),
('The Calculator'),
('The Cheerful Coffin'),
('The Creator'),
('The Creator Incarnate'),
('The Dark - Hex-Sealed Fusion'),
('The Dark Creator'),
('The Dark Door'),
('The Dragon dwelling in the Cave'),
('The Dragon Dwelling in the Cave'),
('The Dragon Dwelling in the Deep'),
('The Dragon''s Bead'),
('The Earl of Demise'),
('The Earth - Hex-Sealed Fusion'),
('The Emperor''s Holiday'),
('The End of Anubis'),
('The Eye of Truth'),
('The Fiend Megacyber'),
('The First Sarcophagus'),
('The Flute of Summoning Dragon'),
('The Flute of Summoning Kuriboh'),
('The Forceful Sentry'),
('The Forces of Darkness'),
('The Forgiving Maiden'),
('The Furious Sea King'),
('The Gift of Greed'),
('The Grave of Enkindling'),
('The Graveyard in the Fourth Dimension'),
('The Gross Ghost of Fled Dreams'),
('The Hunter with 7 Weapons'),
('The Illusory Gentleman'),
('The Immortal Bushi'),
('The Immortal of Thunder'),
('The Inexperienced Spy'),
('The Judgmenet Hand'),
('The Kick Man'),
('The Lady in Wight'),
('The Last Warrior from Another Planet'),
('The Law of the Normal'),
('The League of Uniform Nomenclature'),
('The Legendary Fisherman'),
('The Light - Hex-Sealed Fusion'),
('The Little Swordsman of Aile'),
('The Masked Beast'),
('The Paths of Destiny'),
('The Portrait''s Secret'),
('The Puppet Magic of Dark Ruler'),
('The Regulation of Tribe'),
('The Reliable Guardian'),
('The Rock Spirit'),
('The Sanctuary in the Sky'),
('The Second Sarcophagus'),
('The Secret of the Bandit'),
('The Selection'),
('The Shallow Grave'),
('The Six Samauri - Yariza'),
('The Six Samurai - Irou'),
('The Six Samurai - Kamon'),
('The Six Samurai - Nisashi'),
('The Six Samurai - Yaichi'),
('The Six Samurai - Yariza'),
('The Six Samurai - Zanji'),
('The Spell Absorbing Life'),
('The Statue of Easter Island'),
('The Stern Mystic'),
('The Thing in the Crater'),
('The Third Sarcophagus'),
('The Transmigration Prophecy'),
('The Tricky'),
('The Trojan Horse'),
('The Unfriendly Amazon'),
('The Unhappy Girl'),
('The Unhappy Maiden'),
('The Warrior Returning Alive'),
('The White Stone of Legend'),
('The Wicked Avatar'),
('The Wicked Dreadroot'),
('The Wicked Eraser'),
('The Wicked Worm Beast'),
('The Winged Dragon of Ra'),
('The World Tree'),
('Theban Nightmare'),
('Theinen the Great Sphinx'),
('Thestalos Firestorm Monarch'),
('Thestalos the Firestorm Monarch'),
('Thorn of Malice'),
('Thought Ruler Archfiend'),
('Thousand Dragon'),
('Thousand Energy'),
('Thousand Knives'),
('Thousand Needles'),
('Thousand-Eyes Idol'),
('Thousand-Eyes Jellyfish'),
('Thousand-Eyes Restrict'),
('Threatening Roar'),
('Three-Headed Geedo'),
('Three-Legged Zombies'),
('Throwstone Unit'),
('Thunder Crash'),
('Thunder Dragon'),
('Thunder Kid'),
('Thunder King Rai-Oh'),
('Thunder Nyan Nyan'),
('Thunder of Ruler'),
('Tiger Axe'),
('Tiger Dragon'),
('Time Machine'),
('Time Passage'),
('Time Seal'),
('Time Wizard'),
('Timeater'),
('Timidity'),
('Token Feastevil'),
('Token Thanksgiving'),
('Toll'),
('Tongue Twister'),
('Tongyo'),
('Toon Alligator'),
('Toon Cannon Soldier'),
('Toon Dark Magician Girl'),
('Toon Defense'),
('Toon Gemini Elf'),
('Toon Goblin Attack Force'),
('Toon Masked Sorceror'),
('Toon Mermaid'),
('Toon Summoned Skull'),
('Toon Table of Contents'),
('Toon World'),
('Torando Wall'),
('Torapart'),
('Tornado'),
('Tornado Bird'),
('Tornado Wall'),
('Torpedo Fish'),
('Torrential Tribute'),
('Total Defense Shogun'),
('Totem Dragon'),
('Tour of Doom'),
('Tower of Babel'),
('Toy Magician'),
('Trade-In'),
('Tragedy'),
('Tragoedia'),
('Trakodon'),
('Transcendant Wings'),
('Transcendent Wings'),
('Transmigration Break'),
('Trap Dustshoot'),
('Trap Eater'),
('Trap Hole'),
('Trap Jammer'),
('Trap Master'),
('Trap of Board Eraser'),
('Trap of Darkness'),
('Trap of the Imperial Tomb'),
('Trap Reactor - Y FI'),
('Trap Reclamation'),
('Trap Stun'),
('Treacherous Trap Hole'),
('Treasure Map'),
('Tree Otter'),
('Treeborn Frog'),
('Tremendous Fire'),
('Trent'),
('Tri-Blaze Accelerator'),
('Tri-Horned Dragon'),
('Trial of Nightmare'),
('Trial of the Princess'),
('Triangle Ecstasy Spark'),
('Triangle Power'),
('Tribe Infection Virus'),
('Tribe-Infecting Virus'),
('Tribute Doll'),
('Tribute to The Doomed'),
('Tricky Spell 4'),
('Tricular'),
('Trident Dragion'),
('Triggered Summon'),
('Tripwire Beast'),
('Trojan Blast'),
('Trojan Gladiator Beast'),
('Troop Dragon'),
('Truckroid'),
('Tsukuyomi'),
('Tualatin'),
('Tune Warrior'),
('Tuned Magician'),
('Tuner Capture'),
('Tuner''s Barrier'),
('Tuner''s Scheme'),
('Tuningware'),
('Turbo Booster'),
('Turbo Cannon'),
('Turbo Rocket'),
('Turbo Synchron'),
('Turbo Warrior'),
('Turret Warrior'),
('Turtle Bird'),
('Turtle Oath'),
('Turtle Tiger'),
('Turu-Purun'),
('Tutan Mask'),
('Twilight Rose Knight'),
('Twin Long Rods #2'),
('Twin Swords of Flashing Light - Tryce'),
('Twin-Barrel Dragon'),
('Twin-Headed Behemoth'),
('Twin-Headed Fire Dragon'),
('Twin-Headed Thunder Dragon'),
('Twin-Headed Wolf'),
('Twin-Shield Defender'),
('Twin-Sword Marauder'),
('Twinheaded Beast'),
('Twister'),
('Two Thousand Needles'),
('Two-Headed King Rex'),
('Two-Man Battle Cell'),
('Two-Man Cell Battle'),
('Two-Mouth Darkruler'),
('Two-Pronged Attack'),
('Tyhone'),
('Tyhone #2'),
('Type Zero Magic Crusher'),
('Tyranno Infinity'),
('Tyrant Dragon'),
('Tytannial, Princess of Camellias'),
('UFO Turtle'),
('UFOroid'),
('UFOroid Fighter'),
('Ultimate Ancient Gear Golem'),
('Ultimate Baseball Kid'),
('Ultimate Insect LV1'),
('Ultimate Insect LV3'),
('Ultimate Insect LV5'),
('Ultimate Insect LV7'),
('Ultimate Obedient Fiend'),
('Ultimate Offering'),
('Ultimate Tyranno'),
('Ultra Evolution Pill'),
('Umbral Soul'),
('Umi'),
('Umiiruka'),
('Underground Arachnid'),
('Unicycular'),
('Unifrog'),
('Union Attack'),
('Union Rider'),
('United Resistance'),
('United We Stand'),
('Unity'),
('Unknown Warrior of Fiend'),
('Unleash Your Power!'),
('Unshaven Angler'),
('Unstable Evolution'),
('Updraft'),
('Upstart Goblin'),
('Uraby'),
('Urgent Synthesis'),
('Urgent Tuning'),
('Uria, Lord of Searing Flames'),
('Ushi Oni'),
('V-Tiger Jet'),
('Valhalla, Hall of the Fallen'),
('Valkyrion the Magna Warrior'),
('Vampire Genesis'),
('Vampire Lady'),
('Vampire Lord'),
('Vampire Orchis'),
('Vampire''s Curse'),
('Van''Dalgyon the Dark Dragon Lord'),
('Vanguard of the Dragon'),
('Vanity''s Call'),
('Vanity''s Fiend'),
('Vanity''s Ruler'),
('Vanquishing Light'),
('Variety Comes Out'),
('Vehicroid Connection Zone'),
('Veil of Darkness'),
('Vengeful Bog Spirit'),
('Vengeful Servant'),
('Vengeful Shinobi'),
('Vennominaga the Deity of Poisonous Snakes'),
('Vennominon the King of Poisonous Snakes'),
('Venom Boa'),
('Venom Burn'),
('Venom Cobra'),
('Venom Serpent'),
('Venom Shot'),
('Venom Snake'),
('Venom Swamp'),
('Verdant Sanctuary'),
('Versago the Destroyer'),
('Vicious Claw'),
('Victoria'),
('Victory Dragon'),
('Victory Viper XX03'),
('Vile Germs'),
('Vilepawn Archfiend'),
('Violent Rain'),
('Violet Crystal'),
('Violet Witch'),
('Viper''s Rebirth'),
('Virus Cannon'),
('Viser Des'),
('Volcanic Blaster'),
('Volcanic Counter'),
('Volcanic Doomfire'),
('Volcanic Eruption'),
('Volcanic Hammerer'),
('Volcanic Queen'),
('Volcanic Rat'),
('Volcanic Recharge'),
('Volcanic Rocket'),
('Volcanic Scattershot'),
('Volcanic Shell'),
('Volcanic Slicer'),
('Voltanis the Adjudicator'),
('Voltic Kong'),
('Vorse Raider'),
('Vortex Trooper'),
('VW - Tiger Catapult'),
('VW-Tiger Catapult'),
('VWXYZ - Dragon Catapult Cannon'),
('VWXYZ-Dragon Catapult Cannon'),
('W-Wing Catapult'),
('Waboku'),
('Wall of Illusion'),
('Wall of Ivy'),
('Wall of Revealing Light'),
('Wall of Thorns'),
('Wall Shadow'),
('Wandering Mummy'),
('War–Lion Ritual'),
('Warrior Dai Grepher'),
('Warrior Elimination'),
('Warrior Lady of the Wasteland'),
('Warrior of Atlantis'),
('Warrior of Tradition'),
('Warrior of Zera'),
('Wasteland'),
('Watapon'),
('Water Dragon'),
('Water Hazard'),
('Water Magician'),
('Water Omotics'),
('Water Spirit'),
('Wave-Motion Cannon'),
('Weapon Change'),
('Weather Report'),
('Weed Out'),
('Weeping Idol'),
('Wetlands'),
('Whiptail Crow'),
('Whirlwind Prodigy'),
('Whirlwind Weasel'),
('White Dragon Ritual'),
('White Hole'),
('White Magical Hat'),
('White Magician Pikeru'),
('White Night Dragon'),
('White Ninja'),
('White Potan'),
('White-Horned Dragon'),
('Wicked Rebirth'),
('Wicked-Breaking Flamberge - Baou'),
('Widespread Dud'),
('Widespread Ruin'),
('Wild Fire'),
('Wild Nature''s Release'),
('Wind Effigy'),
('Windstorm of Etaqua'),
('Winged Dragon, Guardian of the Fortress #1'),
('Winged Kuriboh'),
('Winged Kuriboh LV10'),
('Winged Minion'),
('Winged Rhynos'),
('Winged Sage Falcos'),
('Wingweaver'),
('Witch Doctor of Chaos'),
('Witch Doctor of Sparta'),
('Witch of the Black Forest'),
('Witch of the Black Rose'),
('Witch''s Apprentice'),
('Witty Phantom'),
('Wodan the Resident of the Forest'),
('Wolf Axwielder'),
('Wolf in Sheep''s Clothing'),
('Wonder Clover'),
('Wonder Garage'),
('Woodborg Inpachi'),
('Woodland Archer'),
('Woodland Sprite'),
('World Suppression'),
('Worm Apocalypse'),
('Worm Barses'),
('Worm Cartaros'),
('Worm Dimikles'),
('Worm Drake'),
('Worm Erokin'),
('Wow Warrior'),
('Wrath of Neos'),
('Wretched Ghost of the Attic'),
('Wroughtweiler'),
('Wulf, Lightsworn Beast'),
('Wynn the Wind Charmer'),
('X-Head Cannon'),
('X-Saber Airbellum'),
('X-Saber Anu Piranha'),
('X-Saber Axel'),
('X-Saber Galahad'),
('X-Saber Urbellum'),
('X-Saber Uruz'),
('Xing Zhen Hu'),
('Xing-Zhen-Hu'),
('XX-Saber Emmersblade'),
('XX-Saber Faultroll'),
('XX-Saber Fulhelmknight'),
('XX-Saber Gardestrike'),
('XX-Saber Garsem'),
('XX-Saber Gottoms'),
('XX-Saber Hyunlei'),
('XX-Saber Ragigura'),
('XY-Dragon Cannon'),
('XYZ-Dragon Cannon'),
('XZ-Tank Cannon'),
('Y-Dragon Head'),
('Yado Karu'),
('Yamadron'),
('Yamata Dragon'),
('Yamato-no-Kami'),
('Yami'),
('Yaranzo'),
('Yata-Garasu'),
('Yellow Baboon, Archer of the Forest'),
('Yellow Gadget'),
('Yellow Luster Shield'),
('Yomi Ship'),
('Yu-Jo Friendship'),
('Yubel'),
('Yubel - Terror Incarnate'),
('Yubel - Terror Incarnate '),
('Yubel - The Ultimate Nightmare'),
('YZ-Tank Dragon'),
('Z-Metal Tank'),
('Zaborg the Thunder Monarch'),
('Zeman the Ape King'),
('Zera Ritual'),
('Zera the Mant'),
('Zeradias, Herald of Heaven'),
('Zero Gardna'),
('Zero Gravity'),
('Zeta Reticulant'),
('Zoa'),
('Zolga'),
('Zoma the Spirit'),
('Zombie Mammoth'),
('Zombie Master'),
('Zombie Tiger'),
('Zombie World'),
('Zombyra the Dark'),
('Zone Eater'),
('Zure, Knight of Dark World')